# Sarcoma Use Case - Research Question 1

### Algorithms
* Summary 
* Crosstab
* Chi-Squared
* t-test

In [70]:
%reload_ext autoreload
%autoreload 2

In [71]:
from pkg_resources import importlib

from ohdsi import common
from ohdsi import database_connector
import pyarrow as pa

import warnings 
warnings.simplefilter(action='ignore', category=UserWarning)

import pandas as pd
import matplotlib.pyplot as plt
pd.options.mode.chained_assignment = None  # default='warn'

## OMOP database
### Get connection details

In [72]:
import os
os.environ["DATABASE_URI"] = "jdbc:postgresql://localhost:9090/omopdb"
os.environ["DATABASE_TYPE"] = "omop"
os.environ["DB_PARAM_user"] = "ohdsi"
os.environ["DB_PARAM_password"] = "ohdsi"
from vantage6.algorithm.decorator import source_database

@source_database
def print_connection_details(connection_details):
    print(connection_details)
    return connection_details

connection_details = print_connection_details()

{'uri': 'jdbc:postgresql://localhost:9090/omopdb', 'type': 'omop', 'USER': 'ohdsi', 'PASSWORD': 'ohdsi'}

### Connect to the database

In [73]:
conn = database_connector.connect(
    dbms = "postgresql",
    connection_string = connection_details.get('uri'),
    user = connection_details.get('USER'),
    password = connection_details.get('PASSWORD')
)

Connecting using PostgreSQL driver

## Extract the cohort data

In [74]:
sessions = importlib.import_module("v6-sessions")

In [75]:
# rps_cohort
sql = f"SELECT person_id FROM omopcdm.measurement WHERE measurement_concept_id in (36770706)"
df = database_connector.query_sql(conn, sql)
df = common.convert_from_r(df)
pts_RPS = list(df.PERSON_ID.values)

rps_cohort_original = sessions.create_cohort(
    patient_ids=pts_RPS,
    features="sarcoma"
)
rps_cohort = rps_cohort_original.to_pandas()

# pelvis_cohort
sql = f"SELECT person_id FROM omopcdm.measurement WHERE measurement_concept_id in (36768752)"
df = database_connector.query_sql(conn, sql)
df = common.convert_from_r(df)
pts_Pelvis = list(df.PERSON_ID.values)

pelvis_cohort_original = sessions.create_cohort(
    patient_ids=pts_Pelvis,
    features="sarcoma"
)
pelvis_cohort = pelvis_cohort_original.to_pandas()

# rps_pelvis_cohort
sql = f"SELECT person_id FROM omopcdm.measurement WHERE measurement_concept_id in (36770706, 36768752)"
df = database_connector.query_sql(conn, sql)
df = common.convert_from_r(df)
pts_RPS_Pelvis = list(df.PERSON_ID.values)

rps_pelvis_cohort_original = sessions.create_cohort(
    patient_ids=pts_RPS_Pelvis,
    features="sarcoma"
)
rps_pelvis_cohort = rps_pelvis_cohort_original.to_pandas()


print(f'RPS cohort: {len(rps_cohort)}')
print(f'Pelvis cohort: {len(pelvis_cohort)}')
print(f'RPS + Pelvis cohort: {len(rps_pelvis_cohort)}')

info > Setting up connection to database
Connecting using PostgreSQL driver
info > Retrieving variables for cohort: [2.0, 6.0, 9.0, 12.0, 13.0, 14.0, 16.0, 17.0, 19.0, 20.0, 26.0, 27.0, 28.0, 31.0, 32.0, 35.0, 36.0, 37.0, 38.0, 42.0, 44.0, 45.0, 50.0, 52.0, 53.0, 56.0, 58.0, 59.0, 61.0, 65.0, 67.0, 70.0, 73.0, 75.0, 85.0, 86.0, 87.0, 91.0, 92.0, 95.0, 98.0, 99.0, 104.0, 105.0, 107.0, 108.0, 111.0, 112.0, 114.0, 117.0, 119.0, 120.0, 122.0, 124.0, 125.0, 126.0, 133.0, 134.0, 135.0, 138.0, 139.0, 141.0, 142.0, 145.0, 147.0, 149.0, 151.0, 153.0, 155.0, 156.0, 157.0, 159.0, 163.0, 164.0, 165.0, 167.0, 168.0, 170.0, 177.0, 178.0, 179.0, 180.0, 182.0, 183.0, 184.0, 186.0, 190.0, 191.0, 194.0, 195.0, 198.0, 200.0, 202.0, 204.0, 206.0, 207.0, 208.0, 209.0, 210.0, 211.0, 213.0, 214.0, 215.0, 216.0, 218.0, 219.0, 221.0, 223.0, 224.0, 225.0, 227.0, 228.0, 230.0, 234.0, 235.0, 240.0, 242.0, 244.0, 248.0, 249.0, 250.0, 251.0, 253.0, 255.0, 257.0, 258.0, 259.0, 260.0, 261.0, 262.0, 264.0, 265.0, 269.0, 270.0, 273.0, 274.0, 275.0, 278.0, 279.0, 282.0, 284.0, 285.0, 287.0, 291.0, 292.0, 294.0, 295.0, 296.0, 297.0, 299.0, 300.0, 302.0, 304.0, 305.0, 306.0, 307.0, 308.0, 310.0, 311.0, 313.0, 314.0, 315.0, 316.0, 318.0, 320.0, 322.0, 327.0, 328.0, 331.0, 332.0, 334.0, 335.0, 337.0, 339.0, 340.0, 343.0, 345.0, 346.0, 347.0, 349.0, 350.0, 351.0, 353.0, 355.0, 356.0, 357.0, 358.0, 359.0, 360.0, 361.0, 362.0, 363.0, 364.0, 365.0, 366.0, 367.0, 369.0, 371.0, 372.0, 373.0, 375.0, 376.0, 377.0, 378.0, 380.0, 382.0, 383.0, 386.0, 387.0, 388.0, 394.0, 395.0, 396.0, 397.0, 398.0, 399.0, 401.0, 403.0, 405.0, 406.0, 408.0, 409.0, 410.0, 411.0, 412.0, 413.0, 416.0, 420.0, 422.0, 423.0, 424.0, 427.0, 428.0, 429.0, 430.0, 434.0, 438.0, 441.0, 444.0, 445.0, 448.0, 449.0, 451.0, 453.0, 455.0, 456.0, 458.0, 460.0, 461.0, 463.0, 464.0, 466.0, 468.0, 469.0, 471.0, 472.0, 474.0, 476.0, 478.0, 479.0, 480.0, 481.0, 483.0, 484.0, 486.0, 487.0, 488.0, 489.0, 492.0, 496.0, 497.0, 498.0, 499.0, 500.0, 502.0, 503.0, 505.0, 507.0, 509.0, 510.0, 513.0, 516.0, 517.0, 520.0, 521.0, 523.0, 531.0, 532.0, 537.0, 540.0, 543.0, 545.0, 549.0, 550.0, 552.0, 554.0, 555.0, 556.0, 557.0, 560.0, 563.0, 568.0, 570.0, 571.0, 572.0, 573.0, 575.0, 576.0, 577.0, 578.0, 585.0, 586.0, 590.0, 598.0]
info > Loading SQL file: sarcoma
info > -->  Done
info > Injecting patient IDs into SQL
info > -->  Done
info > Executing SQL
info > Converting dataframe to pandas
info > -->  Done
info > Done!
info > Setting up connection to database
Connecting using PostgreSQL driver
info > Retrieving variables for cohort: [1.0, 3.0, 4.0, 5.0, 7.0, 8.0, 10.0, 11.0, 15.0, 18.0, 21.0, 22.0, 23.0, 24.0, 25.0, 29.0, 30.0, 33.0, 34.0, 39.0, 40.0, 41.0, 43.0, 46.0, 47.0, 48.0, 49.0, 51.0, 54.0, 55.0, 57.0, 60.0, 62.0, 63.0, 64.0, 66.0, 68.0, 69.0, 71.0, 72.0, 74.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 88.0, 89.0, 90.0, 93.0, 94.0, 96.0, 97.0, 100.0, 101.0, 102.0, 103.0, 106.0, 109.0, 110.0, 113.0, 115.0, 116.0, 118.0, 121.0, 123.0, 127.0, 128.0, 129.0, 130.0, 131.0, 132.0, 136.0, 137.0, 140.0, 143.0, 144.0, 146.0, 148.0, 150.0, 152.0, 154.0, 158.0, 160.0, 161.0, 162.0, 166.0, 169.0, 171.0, 172.0, 173.0, 174.0, 175.0, 176.0, 181.0, 185.0, 187.0, 188.0, 189.0, 192.0, 193.0, 196.0, 197.0, 199.0, 201.0, 203.0, 205.0, 212.0, 217.0, 220.0, 222.0, 226.0, 229.0, 231.0, 232.0, 233.0, 236.0, 237.0, 238.0, 239.0, 241.0, 243.0, 245.0, 246.0, 247.0, 252.0, 254.0, 256.0, 263.0, 266.0, 267.0, 268.0, 271.0, 272.0, 276.0, 277.0, 280.0, 281.0, 283.0, 286.0, 288.0, 289.0, 290.0, 293.0, 298.0, 301.0, 303.0, 309.0, 312.0, 317.0, 319.0, 321.0, 323.0, 324.0, 325.0, 326.0, 329.0, 330.0, 333.0, 336.0, 338.0, 341.0, 342.0, 344.0, 348.0, 352.0, 354.0, 368.0, 370.0, 374.0, 379.0, 381.0, 384.0, 385.0, 389.0, 390.0, 391.0, 392.0, 393.0, 400.0, 402.0, 404.0, 407.0, 414.0, 415.0, 417.0, 418.0, 419.0, 421.0, 425.0, 426.0, 431.0, 432.0, 433.0, 435.0, 436.0, 437.0, 439.0, 440.0, 442.0, 443.0, 446.0, 447.0, 450.0, 452.0, 454.0, 457.0, 459.0, 462.0, 465.0, 467.0, 470.0, 473.0, 475.0, 477.0, 482.0, 485.0, 490.0, 491.0, 493.0, 494.0, 495.0, 501.0, 504.0, 506.0, 508.0, 511.0, 512.0, 514.0, 515.0, 518.0, 519.0, 522.0, 524.0, 525.0, 526.0, 527.0, 528.0, 529.0, 530.0, 533.0, 534.0, 535.0, 536.0, 538.0, 539.0, 541.0, 542.0, 544.0, 546.0, 547.0, 548.0, 551.0, 553.0, 558.0, 559.0, 561.0, 562.0, 564.0, 565.0, 566.0, 567.0, 569.0, 574.0, 579.0, 580.0, 581.0, 582.0, 583.0, 584.0, 587.0, 588.0, 589.0, 591.0, 592.0, 593.0, 594.0, 595.0, 596.0, 597.0, 599.0, 600.0]
info > Loading SQL file: sarcoma
info > -->  Done
info > Injecting patient IDs into SQL
info > -->  Done
info > Executing SQL
info > Converting dataframe to pandas
info > -->  Done
info > Done!
info > Setting up connection to database
Connecting using PostgreSQL driver
info > Retrieving variables for cohort: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0, 92.0, 93.0, 94.0, 95.0, 96.0, 97.0, 98.0, 99.0, 100.0, 101.0, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 108.0, 109.0, 110.0, 111.0, 112.0, 113.0, 114.0, 115.0, 116.0, 117.0, 118.0, 119.0, 120.0, 121.0, 122.0, 123.0, 124.0, 125.0, 126.0, 127.0, 128.0, 129.0, 130.0, 131.0, 132.0, 133.0, 134.0, 135.0, 136.0, 137.0, 138.0, 139.0, 140.0, 141.0, 142.0, 143.0, 144.0, 145.0, 146.0, 147.0, 148.0, 149.0, 150.0, 151.0, 152.0, 153.0, 154.0, 155.0, 156.0, 157.0, 158.0, 159.0, 160.0, 161.0, 162.0, 163.0, 164.0, 165.0, 166.0, 167.0, 168.0, 169.0, 170.0, 171.0, 172.0, 173.0, 174.0, 175.0, 176.0, 177.0, 178.0, 179.0, 180.0, 181.0, 182.0, 183.0, 184.0, 185.0, 186.0, 187.0, 188.0, 189.0, 190.0, 191.0, 192.0, 193.0, 194.0, 195.0, 196.0, 197.0, 198.0, 199.0, 200.0, 201.0, 202.0, 203.0, 204.0, 205.0, 206.0, 207.0, 208.0, 209.0, 210.0, 211.0, 212.0, 213.0, 214.0, 215.0, 216.0, 217.0, 218.0, 219.0, 220.0, 221.0, 222.0, 223.0, 224.0, 225.0, 226.0, 227.0, 228.0, 229.0, 230.0, 231.0, 232.0, 233.0, 234.0, 235.0, 236.0, 237.0, 238.0, 239.0, 240.0, 241.0, 242.0, 243.0, 244.0, 245.0, 246.0, 247.0, 248.0, 249.0, 250.0, 251.0, 252.0, 253.0, 254.0, 255.0, 256.0, 257.0, 258.0, 259.0, 260.0, 261.0, 262.0, 263.0, 264.0, 265.0, 266.0, 267.0, 268.0, 269.0, 270.0, 271.0, 272.0, 273.0, 274.0, 275.0, 276.0, 277.0, 278.0, 279.0, 280.0, 281.0, 282.0, 283.0, 284.0, 285.0, 286.0, 287.0, 288.0, 289.0, 290.0, 291.0, 292.0, 293.0, 294.0, 295.0, 296.0, 297.0, 298.0, 299.0, 300.0, 301.0, 302.0, 303.0, 304.0, 305.0, 306.0, 307.0, 308.0, 309.0, 310.0, 311.0, 312.0, 313.0, 314.0, 315.0, 316.0, 317.0, 318.0, 319.0, 320.0, 321.0, 322.0, 323.0, 324.0, 325.0, 326.0, 327.0, 328.0, 329.0, 330.0, 331.0, 332.0, 333.0, 334.0, 335.0, 336.0, 337.0, 338.0, 339.0, 340.0, 341.0, 342.0, 343.0, 344.0, 345.0, 346.0, 347.0, 348.0, 349.0, 350.0, 351.0, 352.0, 353.0, 354.0, 355.0, 356.0, 357.0, 358.0, 359.0, 360.0, 361.0, 362.0, 363.0, 364.0, 365.0, 366.0, 367.0, 368.0, 369.0, 370.0, 371.0, 372.0, 373.0, 374.0, 375.0, 376.0, 377.0, 378.0, 379.0, 380.0, 381.0, 382.0, 383.0, 384.0, 385.0, 386.0, 387.0, 388.0, 389.0, 390.0, 391.0, 392.0, 393.0, 394.0, 395.0, 396.0, 397.0, 398.0, 399.0, 400.0, 401.0, 402.0, 403.0, 404.0, 405.0, 406.0, 407.0, 408.0, 409.0, 410.0, 411.0, 412.0, 413.0, 414.0, 415.0, 416.0, 417.0, 418.0, 419.0, 420.0, 421.0, 422.0, 423.0, 424.0, 425.0, 426.0, 427.0, 428.0, 429.0, 430.0, 431.0, 432.0, 433.0, 434.0, 435.0, 436.0, 437.0, 438.0, 439.0, 440.0, 441.0, 442.0, 443.0, 444.0, 445.0, 446.0, 447.0, 448.0, 449.0, 450.0, 451.0, 452.0, 453.0, 454.0, 455.0, 456.0, 457.0, 458.0, 459.0, 460.0, 461.0, 462.0, 463.0, 464.0, 465.0, 466.0, 467.0, 468.0, 469.0, 470.0, 471.0, 472.0, 473.0, 474.0, 475.0, 476.0, 477.0, 478.0, 479.0, 480.0, 481.0, 482.0, 483.0, 484.0, 485.0, 486.0, 487.0, 488.0, 489.0, 490.0, 491.0, 492.0, 493.0, 494.0, 495.0, 496.0, 497.0, 498.0, 499.0, 500.0, 501.0, 502.0, 503.0, 504.0, 505.0, 506.0, 507.0, 508.0, 509.0, 510.0, 511.0, 512.0, 513.0, 514.0, 515.0, 516.0, 517.0, 518.0, 519.0, 520.0, 521.0, 522.0, 523.0, 524.0, 525.0, 526.0, 527.0, 528.0, 529.0, 530.0, 531.0, 532.0, 533.0, 534.0, 535.0, 536.0, 537.0, 538.0, 539.0, 540.0, 541.0, 542.0, 543.0, 544.0, 545.0, 546.0, 547.0, 548.0, 549.0, 550.0, 551.0, 552.0, 553.0, 554.0, 555.0, 556.0, 557.0, 558.0, 559.0, 560.0, 561.0, 562.0, 563.0, 564.0, 565.0, 566.0, 567.0, 568.0, 569.0, 570.0, 571.0, 572.0, 573.0, 574.0, 575.0, 576.0, 577.0, 578.0, 579.0, 580.0, 581.0, 582.0, 583.0, 584.0, 585.0, 586.0, 587.0, 588.0, 589.0, 590.0, 591.0, 592.0, 593.0, 594.0, 595.0, 596.0, 597.0, 598.0, 599.0, 600.0]
info > Loading SQL file: sarcoma
info > -->  Done
info > Injecting patient IDs into SQL
info > -->  Done
info > Executing SQL
info > Converting dataframe to pandas
info > -->  Done
info > Done!
RPS cohort: 314
Pelvis cohort: 286
RPS + Pelvis cohort: 600

## MockClient
We mock to have two organizations with three databases each (<code>rps_cohort</code>, <code>pelvis_cohort</code> and <code>rps_pelvis_cohort</code>). <br><br>
The first organization has:
* <code>rps_cohort[:10]</code> (10 pts)
* <code>pelvis_cohort[:10]</code> (10 pts)
* <code>rps_pelvis_cohort[:10]</code> (10 pts)

The second organization has:
* <code>rps_cohort[10:]</code> (304 pts)
* <code>pelvis_cohort[10:]</code> (276 pts)
* <code>non_liposarcoma_cohort[10:]</code> (590 pts)

In [76]:
from vantage6.algorithm.tools.mock_client import MockAlgorithmClient

client = MockAlgorithmClient(
    datasets=[
        [
            {
                "database": {
                    "rps_cohort": rps_cohort[:10],
                    "pelvis_cohort": pelvis_cohort[:10],
                    "rps_pelvis_cohort": rps_pelvis_cohort[:10],
                },
                "db_type": "omop"
            },
        ],
        [
            {
                "database": {
                    "rps_cohort": rps_cohort[10:],
                    "pelvis_cohort": pelvis_cohort[10:],
                    "rps_pelvis_cohort": rps_pelvis_cohort[10:],
                },
                "db_type": "omop"
            },
        ]
    ],
    module="v6-analytics",
)

## Research question 1
### What are the characteristics of patients diagnosed with retroperitoneal sarcoma (RPS)?

<b>Steps</b>

1. Descriptive statistics of relevant variables <br>
    a. Table1 cohorts (Summary algorithm) <br>
    b. Table1 centers (per cohort) (Summary algorithm) <br>
2.  Combined variables <br>
    a.	Age (Mean + other stats if possible) vs Histology (Stratified summary algorithm) <br>
    b.	FNCLCC Grade vs Histology (Cross tabulation algorithm) <br>
    c.	Post-operative Radiotherapy vs Histology (Cross tabulation algorithm) <br>
3. Across center differences <br>
    a. Chi-squared for categorial variables <br>
    b. T-test for continous variables <br>

    <b>Relevant variables (<code>COLUMN</code>)</b>

    * Age (mean, median per center, IQR) (<code>AGE</code> - num)
    * Tumor size (mean, median per center, IQR) (<code>TUMOR_SIZE</code> - num)
    * Histology subgroup (subgroup frequencies) (<code>HISTOLOGY</code> - cat)
    * Sex (Male/Female) (<code>SEX</code> - cat)
    * FNCLCC grade (frequencies) (<code>FNCLCC_GRADE</code> - cat)
    * Multifocality (Unifocal/Multifocal) (<code>MULTIFOCALITY</code> - cat)     
    * Completeness of resection (R0/R1, R2) (<code>COMPLETENESS_OF_RESECTION</code> - cat)
    * Tumor rupture (Yes/No) (<code>TUMOR_RUPTURE</code> - cat)          
    * Pre-operative Chemotherapy (Yes/No) (<code>PRE_OPERATIVE_CHEMO</code> - cat)
    * Post-operative Chemotherapy (Yes/No) (<code>POST_OPERATIVE_CHEMO</code> - cat)
    * Pre-operative Radiotherapy (Yes/No) (<code>PRE_OPERATIVE_RADIO</code> - cat)
    * Post-operative Radiotherapy (Yes/No) (<code>POST_OPERATIVE_RADIO</code> - cat)
    * Local recurrence (Yes/No) (<code>LOCAL_RECURRENCE</code> - cat)  
    * Distant metastases (Yes/No) (<code>DISTANT_METASTASIS</code> - cat)
    * Status (Alive/Dead) (<code>STATUS</code> - cat)
    
    > TODO: How do we calculate the following three?
    * Number of patients (Summary gives this back) #TODO
    * Number of RPS tumors (<code>N_CANCER_EPISODES</code>)
    * Number of deaths (Should be calculated from <code>STATUS</code>) #TODO

    > TODO: The following two variables were requested in the use case but we couldn't link them to the IDEA4RC-DM:
    * N. of surgeries in/outside the center per year
    * Hospital Volume (HV) as High vs Low

## 1. Descriptive statistics
(Summary algorithm)

### 1a. Table1 cohorts

<!-- <img src="../table1%20overall.PNG" alt="Data Preparation Categorical" width="700"/> -->

In [77]:
#TODO Delete this cell?
import os
os.environ["CONTAINER_TOKEN"] = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOnsidmFudGFnZTZfY2xpZW50X3R5cGUiOiJjb250YWluZXIiLCJub2RlX2lkIjoxLCJvcmdhbml6YXRpb25faWQiOjEsImNvbGxhYm9yYXRpb25faWQiOjMsInN0dWR5X2lkIjoyLCJzdG9yZV9pZCI6Miwic2Vzc2lvbl9pZCI6NCwidGFza19pZCI6NDQsImltYWdlIjoibW9jay1jbGllbnQiLCJkYXRhYmFzZXMiOiJhIn19.AHhYhzj9P6wPGa2DAh-2uq29zfRDQLGeFtzvR0eOgW4"
os.environ["SESSION_FOLDER"] = "henk"
os.environ["INPUT_FILE"] = "henk"
os.environ["OUTPUT_FILE"] = "henk"

In [78]:
numeric_columns = ["AGE", "TUMOR_SIZE"]

relevant_variables = [
    "AGE", # num
    "TUMOR_SIZE", # num
    "HISTOLOGY", # cat
    "SEX", # cat
    "FNCLCC_GRADE", # cat
    "MULTIFOCALITY", # cat
    "COMPLETENESS_OF_RESECTION", # cat
    "TUMOR_RUPTURE", # cat
    "PRE_OPERATIVE_CHEMO", # cat
    "POST_OPERATIVE_CHEMO", # cat
    "PRE_OPERATIVE_RADIO", # cat
    "POST_OPERATIVE_RADIO", # cat
    "LOCAL_RECURRENCE", # cat
    "DISTANT_METASTASIS", # cat
    "STATUS", # cat
    ]

# overall summary results
input_ = {
        "kwargs":{
            "columns": relevant_variables,
            "numeric_columns": numeric_columns,
        }
    }

task = client.task.create(
    method="summary",
    organizations=[0],
    input_=input_
)

client.wait_for_results(task_id=task.get("id"))
result = client.result.from_task(task_id=task.get("id"))

# summary results per center
input_centers = {
        "kwargs":{
            "columns": relevant_variables,
            "numeric_columns": numeric_columns,
        }
    }

task_centers = client.task.create(
    method="summary_per_data_station",
    organizations=[0,1],
    input_=input_centers,
    name="Subtask summary",
    description="Compute summary per data station",
)

client.wait_for_results(task_id=task_centers.get("id"))
result_centers = client.result.from_task(task_id=task_centers.get("id"))

info > Defining input parameters
info > Creating subtask for all organizations in the collaboration
info > Extracting payload from token
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Extracting payload from token
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Waiting for results
info > Mocking waiting for results
info > Results obtained!
info > Aggregating partial summaries
info > n num cols: 2
info > n means: 2
info > Aggregating partial summaries
info > n num cols: 2
info > n means: 2
info > Aggregating partial summaries
info > n num cols: 2
info > n means: 2
info > {'columns': ['AGE', 'TUMOR_SIZE']}
info > {'pelvis_cohort': [47.53496503496503, 5.479282868525896], 'rps_cohort': [45.46496815286624, 5.391958041958042], 'rps_pelvis_cohort': [46.45166666666667, 5.432774674115456]}
info > Cake is a lie
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > {'rps_cohort': {'AGE': 3496.2256480993146, 'TUMOR_SIZE': 58.57135128857158}, 'pelvis_cohort': {'AGE': 3044.1765612010367, 'TUMOR_SIZE': 54.89795368327487}, 'rps_pelvis_cohort': {'AGE': 1938.6733611111108, 'TUMOR_SIZE': 52.589418696184396}}
info > {'columns': ['AGE', 'TUMOR_SIZE']}
info > {'pelvis_cohort': [47.53496503496503, 5.479282868525896], 'rps_cohort': [45.46496815286624, 5.391958041958042], 'rps_pelvis_cohort': [46.45166666666667, 5.432774674115456]}
info > Cake is a lie
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > {'rps_cohort': {'AGE': 84139.88900158221, 'TUMOR_SIZE': 1962.880152207932}, 'pelvis_cohort': {'AGE': 74696.97378844931, 'TUMOR_SIZE': 1821.8143172330597}, 'rps_pelvis_cohort': {'AGE': 164079.92497222224, 'TUMOR_SIZE': 3846.5937470393837}}
info > Hello!
info > Mocking waiting for results
info > Goodbye!
info > Mocking waiting for results
info > Extracting payload from token
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Extracting payload from token
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Mocking waiting for results

In [79]:
def fmt_mean_sd(stats):
    return f"{round(stats['mean'], 1)}"

def fmt_int(value):
    return f"{int(value)}"

def format_val(count, total):
        pct = (count / total * 100) if total > 0 else 0
        return f"{int(count)} ({pct:.1f}%)"


def get_numeric_rows(result, cohorts, var):
    """Return numeric summary rows (mean±SD, min, max)."""
    def numeric(cohort):
        return result[0][cohort]['numeric'][var]

    return [
        ("Mean (SD)", True, " ", *[fmt_mean_sd(numeric(c)) for c in cohorts]),
        ("Min", True, " ", *[fmt_int(numeric(c)['min']) for c in cohorts]),
        ("Max", True, " ", *[fmt_int(numeric(c)['max']) for c in cohorts]),
        ("Missing", True, " ", *[format_val(numeric(c)['missing'], numeric(c)['count']) for c in cohorts]),
    ]


def get_categorical_rows(result, cohorts, var, levels):
    """
    Return categorical summary rows with counts and percentages,
    plus a 'Missing' row based on any 'N/A' keys.
    """
    def val(cohort, key):
        return result[0][cohort]['counts_unique_values'][var].get(key, 0)

    def format_val(count, total):
        pct = (count / total * 100) if total > 0 else 0
        return f"{count} ({pct:.1f}%)"

    # Calculate total per cohort (including N/A)
    totals = []
    for c in cohorts:
        total = sum(result[0][c]['counts_unique_values'][var].values())
        totals.append(total)

    rows = []
    # Normal levels
    for level in levels:
        rows.append(
            (
                level,
                True,
                " ",
                *[format_val(val(c, level), totals[i]) for i, c in enumerate(cohorts)],
            )
        )

    # Automatically detect missing
    missing_keys = [
        k for k in result[0][cohorts[0]]['counts_unique_values'][var].keys() if 'N/A' in k
    ]
    if missing_keys:
        missing_counts = [sum(val(c, k) for k in missing_keys) for c in cohorts]
    else:
        missing_counts = [0, 0, 0]

    rows.append(
        (
            "Missing",
            True,
            " ",
            *[format_val(missing_counts[i], totals[i]) for i in range(len(cohorts))],
        )
    )

    return rows


def make_data(result, cohort1, cohort2, cohort3, var1, var2):
    """Generate clean descriptive summary data (numeric + categorical)."""
    cohorts = [cohort1, cohort2, cohort3]
    data = []

    # Numeric examples
    data.append(("Age (y)", False, "", "", "", ""))
    data += get_numeric_rows(result, cohorts, var1)

    data.append(("Tumor size (mm)", False, "", "", "", ""))
    data += get_numeric_rows(result, cohorts, var2)

    # Categorical examples
    categorical_blocks = [
        ("Sex", "SEX", ["FEMALE", "MALE"]),
        ("FNCLCC grade", "FNCLCC_GRADE", ["Grade 1 tumor", "Grade 2 tumor", "Grade 3 tumor"]),
        ("Multifocality", "MULTIFOCALITY", ["MULTIFOCAL TUMOR"]),
        ("Completeness of resection", "COMPLETENESS_OF_RESECTION", ["Macroscopically complete", "Macroscopically incomplete"]),
        ("Tumor rupture", "TUMOR_RUPTURE", ["1.0", "0.0"]),
        ("Chemotherapy", "POST_OPERATIVE_CHEMO", ["1.0", "0.0"]),
        ("Radiotherapy", "POST_OPERATIVE_RADIO", ["1.0", "0.0"]),
        ("Local recurrence", "LOCAL_RECURRENCE", ["1.0", "0.0"]),
        ("Distant metastasis", "DISTANT_METASTASIS", ["1.0", "0.0"]),
        ("Status", "STATUS", ["ALIVE", "DEAD"]),
    ]

    for label, var, levels in categorical_blocks:
        data.append((label, False, "", "", "", ""))
        rows = get_categorical_rows(result, cohorts, var, levels)
        data.extend(rows)

    return data


# RUN
cohort1 = 'rps_cohort'
cohort2 = 'pelvis_cohort'
cohort3 = 'rps_pelvis_cohort'

var1 = 'AGE'
var2 = 'TUMOR_SIZE'
data = make_data(result, cohort1, cohort2, cohort3, var1, var2)

In [80]:
# #TODO: Note that in OMOP some items are recorded IF availabe, but not recorded as 'N/A' if not available, so how do we decide missing? Example: If someone had radiotherapy this is registered. If someone did not have radiotherapy nothing is registered. So is this 'No radiotherapy' or missing value?
# #TODO: Local Recurrence not added to the data

df_filled = pd.DataFrame(data, columns=["Characteristic", "is_sub", "Total (n=XXX)", f"{cohort1} (n={result[0][cohort1]['categorical']['SEX']['count']})", f"{cohort2} (n={result[0][cohort2]['categorical']['SEX']['count']})", f"{cohort3} (n={result[0][cohort3]['categorical']['SEX']['count']})"])
df_filled.drop(columns=["Total (n=XXX)"], inplace=True)

# Apply styling function as before
def style_rows(row):
    idx = row.name
    if not df_filled.loc[idx, "is_sub"]:
        return ["font-weight: bold; background-color: #f2f2f2"] * len(row)
    else:
        return ["padding-left: 20px"] + [""] * (len(row) - 1)

styled_df = (
    df_filled.drop(columns=["is_sub"]).style
    .apply(style_rows, axis=1)
    .hide(axis="index")
    .set_properties(subset=["Characteristic"], **{"text-align": "left"})
    .set_table_styles([{"selector": "th", "props": [("font-weight", "bold"),
                                                    ("background-color", "#d9d9d9"),
                                                    ("text-align", "center")]}])
)

styled_df

In [89]:
len(df_filled)

50

In [99]:
# # import dataframe_image as dfi

# # # Save as PNG
# # dfi.export(styled_df, "table1_v1.pdf", table_conversion="chrome")


# # html = styled_df.to_html()
# # with open("table1_v1.html", "w", encoding="utf-8") as f:
# #     f.write(html)


# import dataframe_image as dfi

# # dfi.export(
# #     styled_df,
# #     "table1_v2.png",
# #     table_conversion="chrome",
# #     chrome_path=None,       # optional, if chrome is in PATH
# #     max_rows=-1,            # show all rows
# #     max_cols=-1,            # show all columns
# # )



styled_df = (
    df_filled[:22].drop(columns=["is_sub"]).style
    .apply(style_rows, axis=1)
    .hide(axis="index")
    .set_properties(subset=["Characteristic"], **{"text-align": "left"})
    .set_table_styles([{"selector": "th", "props": [("font-weight", "bold"),
                                                    ("background-color", "#d9d9d9"),
                                                    ("text-align", "center")]}])
)

dfi.export(
    styled_df,
    "table1_v8.png",
    table_conversion="chrome",
    # chrome_path=None,       # optional, if chrome is in PATH
    max_rows=-1,            # show all rows
    max_cols=-1,            # show all columns
    dpi=300
)


styled_df = (
    df_filled[22:].drop(columns=["is_sub"]).style
    .apply(style_rows, axis=1)
    .hide(axis="index")
    .set_properties(subset=["Characteristic"], **{"text-align": "left"})
    .set_table_styles([{"selector": "th", "props": [("font-weight", "bold"),
                                                    ("background-color", "#d9d9d9"),
                                                    ("text-align", "center")]}])
)

dfi.export(
    styled_df,
    "table1_v9.png",
    table_conversion="chrome",
    # chrome_path=None,       # optional, if chrome is in PATH
    max_rows=-1,            # show all rows
    max_cols=-1,            # show all columns
    dpi=300
)

# styled_df = (
#     df_filled.drop(columns=["is_sub"]).style
#     .apply(style_rows, axis=1)
#     .hide(axis="index")
#     .set_properties(subset=["Characteristic"], **{"text-align": "left"})
#     .set_table_styles([{"selector": "th", "props": [("font-weight", "bold"),
#                                                     ("background-color", "#d9d9d9"),
#                                                     ("text-align", "center")]}])
# )

# dfi.export(
#     styled_df,
#     "table1_v7.pdf",
#     table_conversion="chrome",
#     # chrome_path=None,       # optional, if chrome is in PATH
#     max_rows=-1,            # show all rows
#     max_cols=-1,            # show all columns
#     dpi=300,
#     chrome_args=["--window_sizze=1920,20000"]
# )

# html = styled_df.to_html(
#     doctype_html=True,
#     notebook=False,
#     border=0,
#     table_uuid='styled_table'

# )
# with open("table1_v7.html", "w", encoding="utf-8") as f:
#     f.write(html)

### 1b. Table1 centers (per cohort)

<!-- <img src="../table1%20per%20cohort%20and%20centers.PNG" alt="Data Preparation Categorical" width="700"/> -->

In [12]:
#TODO: finalize this one when Summary results also outputs center name @FRANK

In [13]:
# #TODO: This now is just a copy of the previous table with some columns renamed
# #TODO: do dit

# import pandas as pd

# cohort1 = 'rps_cohort'
# cohort2 = 'pelvis_cohort'

# var1 = 'AGE'
# var2 = 'TUMOR_SIZE'

# # Pre-filled data from your dataset
# data = [
#     # Characteristic, is_sub, Total, Cohort1, Cohort2
    
#     ("Age (y)", False, "", "", ""),
#     ("Mean (SD)", True, " ", f"{round(result[0][cohort1]['numeric'][var1]['mean'], 1)} ({round(result[0][cohort1]['numeric'][var1]['std'], 1)})", f"{round(result[0][cohort2]['numeric'][var1]['mean'], 1)} ({round(result[0][cohort2]['numeric'][var1]['std'], 1)})"),
#     ("Min", True, " ", f"{int(result[0][cohort1]['numeric'][var1]['min'])}", f"{int(result[0][cohort2]['numeric'][var1]['min'])}"),
#     ("Max", True, " ", f"{int(result[0][cohort1]['numeric'][var1]['max'])}", f"{int(result[0][cohort2]['numeric'][var1]['max'])}"),
#     ("Q1; Q3", True, " ", f"{int(result[0][cohort1]['numeric'][var1]['q_25'][0])}, {int(result[0][cohort1]['numeric'][var1]['q_75'][0])}", f"{int(result[0][cohort2]['numeric'][var1]['q_25'][0])}, {int(result[0][cohort2]['numeric'][var1]['q_75'][0])}"),
    
#     ("Tumor size (mm)", False, "", "", ""),
#     ("Mean (SD)", True, " ", f"{round(result[0][cohort1]['numeric'][var2]['mean'], 1)} ({round(result[0][cohort1]['numeric'][var2]['std'], 1)})", f"{round(result[0][cohort2]['numeric'][var2]['mean'], 1)} ({round(result[0][cohort2]['numeric'][var2]['std'], 1)})"),
#     ("Min", True, " ", f"{int(result[0][cohort1]['numeric'][var2]['min'])}", f"{int(result[0][cohort2]['numeric'][var2]['min'])}"),
#     ("Max", True, " ", f"{int(result[0][cohort1]['numeric'][var2]['max'])}", f"{int(result[0][cohort2]['numeric'][var2]['max'])}"),
#     ("Q1; Q3", True, " ", f"{int(result[0][cohort1]['numeric'][var2]['q_25'][0])}, {int(result[0][cohort1]['numeric'][var2]['q_75'][0])}", f"{int(result[0][cohort2]['numeric'][var2]['q_25'][0])}, {int(result[0][cohort2]['numeric'][var2]['q_75'][0])}"),
    
#     ("Sex", False, "", "", ""),
#     ("Female", True, " ", result[0][cohort1]['counts_unique_values']['SEX']['FEMALE'], result[0][cohort2]['counts_unique_values']['SEX']['FEMALE']),
#     ("Male", True, " ", result[0][cohort1]['counts_unique_values']['SEX']['MALE'], result[0][cohort2]['counts_unique_values']['SEX']['MALE']),
    
#     ("FNCLCC grade", False, "", "", ""),
#     ("Grade 1 tumor", True, " ", result[0][cohort1]['counts_unique_values']['FNCLCC_GRADE']['Grade 1 tumor'], result[0][cohort2]['counts_unique_values']['FNCLCC_GRADE']['Grade 1 tumor']),
#     ("Grade 2 tumor", True, " ", result[0][cohort1]['counts_unique_values']['FNCLCC_GRADE']['Grade 2 tumor'], result[0][cohort2]['counts_unique_values']['FNCLCC_GRADE']['Grade 2 tumor']),
#     ("Grade 3 tumor", True, " ", result[0][cohort1]['counts_unique_values']['FNCLCC_GRADE']['Grade 3 tumor'], result[0][cohort2]['counts_unique_values']['FNCLCC_GRADE']['Grade 3 tumor']),
#     ("Missing", True, " ", result[0][cohort1]['counts_unique_values']['FNCLCC_GRADE']['N/A'], result[0][cohort2]['counts_unique_values']['FNCLCC_GRADE']['N/A']),
    
#     ("Multifocality", False, "", "", ""),
#     ("Yes", True, " ", result[0][cohort1]['counts_unique_values']['MULTIFOCALITY']['MULTIFOCAL TUMOR'], result[0][cohort2]['counts_unique_values']['MULTIFOCALITY']['MULTIFOCAL TUMOR']),
#     ("No", True, " ", result[0][cohort1]['counts_unique_values']['MULTIFOCALITY']['N/A'], result[0][cohort2]['counts_unique_values']['MULTIFOCALITY']['N/A']), 
#     ("Missing", True, " ", "0", "0"),
    
#     ("Completeness of resection", False, "", "", ""),
#     ("Macroscopically complete", True, " ", result[0][cohort1]['counts_unique_values']['COMPLETENESS_OF_RESECTION']['Macroscopically complete'], result[0][cohort2]['counts_unique_values']['COMPLETENESS_OF_RESECTION']['Macroscopically complete']),
#     ("Macroscopically incomplete", True, " ", result[0][cohort1]['counts_unique_values']['COMPLETENESS_OF_RESECTION']['Macroscopically incomplete'], result[0][cohort2]['counts_unique_values']['COMPLETENESS_OF_RESECTION']['Macroscopically incomplete']),
#     ("Missing", True, " ", result[0][cohort1]['counts_unique_values']['COMPLETENESS_OF_RESECTION']['N/A2'], result[0][cohort2]['counts_unique_values']['COMPLETENESS_OF_RESECTION']['N/A']),
    
#     ("Tumor rupture", False, "", "", ""),
#     ("Yes", True, " ", result[0][cohort1]['counts_unique_values']['TUMOR_RUPTURE']['1.0'], result[0][cohort2]['counts_unique_values']['TUMOR_RUPTURE']['1.0']),
#     ("No", True, " ", result[0][cohort1]['counts_unique_values']['TUMOR_RUPTURE']['0.0'], result[0][cohort2]['counts_unique_values']['TUMOR_RUPTURE']['0.0']), 
#     ("Missing", True, " ", "0", "0"),
    
#     ("Chemotherapy", False, "", "", ""), # just post-op? or combined with pre-op?
#     ("Yes", True, " ", result[0][cohort1]['counts_unique_values']['POST_OPERATIVE_CHEMO']['1.0'], result[0][cohort2]['counts_unique_values']['POST_OPERATIVE_CHEMO']['1.0']),
#     ("No", True, " ", result[0][cohort1]['counts_unique_values']['POST_OPERATIVE_CHEMO']['0.0'], result[0][cohort2]['counts_unique_values']['POST_OPERATIVE_CHEMO']['0.0']),  
#     ("Missing", True, " ", "0", "0"),
    
#     ("Radiotherapy", False, "", "", ""), # just post-op? or combined with pre-op?
#     ("Yes", True, " ", result[0][cohort1]['counts_unique_values']['POST_OPERATIVE_RADIO']['1.0'], result[0][cohort2]['counts_unique_values']['POST_OPERATIVE_RADIO']['1.0']),
#     ("No", True, " ", result[0][cohort1]['counts_unique_values']['POST_OPERATIVE_RADIO']['0.0'], result[0][cohort2]['counts_unique_values']['POST_OPERATIVE_RADIO']['0.0']),  
#     ("Missing", True, " ", "0", "0"),

#     ("Local recurrence", False, "", "", ""),
#     ("Yes", True, " ", 0 if not '1.0' in result[0][cohort1]['counts_unique_values']['LOCAL_RECURRENCE'].keys() else result[0][cohort1]['counts_unique_values']['LOCAL_RECURRENCE']['1.0'], 0 if not '1.0' in result[0][cohort1]['counts_unique_values']['LOCAL_RECURRENCE'].keys() else result[0][cohort1]['counts_unique_values']['LOCAL_RECURRENCE']['1.0']), # if else moet eigenlijk bij allemaal
#     ("No", True, " ", result[0][cohort1]['counts_unique_values']['LOCAL_RECURRENCE']['0.0'], result[0][cohort2]['counts_unique_values']['LOCAL_RECURRENCE']['0.0']),  
#     ("Missing", True, " ", "0", "0"),
    
#     ("Distant metastasis", False, "", "", ""),
#     ("Yes", True, " ", result[0][cohort1]['counts_unique_values']['DISTANT_METASTASIS']['1.0'], result[0][cohort2]['counts_unique_values']['DISTANT_METASTASIS']['1.0']),
#     ("No", True, " ", result[0][cohort1]['counts_unique_values']['DISTANT_METASTASIS']['0.0'], result[0][cohort2]['counts_unique_values']['DISTANT_METASTASIS']['0.0']),
#     ("Missing", True, " ", "0", "0"),
    
#     ("Status", False, "", "", ""),
#     ("Alive", True, " ", result[0][cohort1]['counts_unique_values']['STATUS']['ALIVE'], result[0][cohort2]['counts_unique_values']['STATUS']['ALIVE']),
#     ("Dead", True, " ", result[0][cohort1]['counts_unique_values']['STATUS']['DEAD'], result[0][cohort2]['counts_unique_values']['STATUS']['DEAD']),
#     ("Missing", True, " ", "0", "0"),
# ]

# df_filled = pd.DataFrame(data, columns=["Characteristic", "is_sub", f"Total (n={result[0][cohort1]['categorical']['SEX']['count']+result[0][cohort2]['categorical']['SEX']['count']})", f"INT (n={result[0][cohort1]['categorical']['SEX']['count']})", f"ISS-FJD (n={result[0][cohort2]['categorical']['SEX']['count']})"])
# df_filled.drop(columns=[df_filled.columns[i] for i in range(len(df_filled.columns)) if df_filled.columns[i].startswith('Total')], inplace=True)

# # Apply styling function as before
# def style_rows(row):
#     idx = row.name
#     if not df_filled.loc[idx, "is_sub"]:
#         return ["font-weight: bold; background-color: #f2f2f2"] * len(row)
#     else:
#         return ["padding-left: 20px"] + [""] * (len(row) - 1)

# styled_df = (
#     df_filled.drop(columns=["is_sub"]).style
#     .apply(style_rows, axis=1)
#     .hide(axis="index")
#     .set_properties(subset=["Characteristic"], **{"text-align": "left"})
#     .set_table_styles([{"selector": "th", "props": [("font-weight", "bold"),
#                                                     ("background-color", "#d9d9d9"),
#                                                     ("text-align", "center")]}])
# )

# print(f'{cohort1}')
# display(styled_df)

# print(f'{cohort2}')
# display(styled_df)

## 2. Combined variables
(Crosstab algorithm)
(link)

### 2a.	Age vs Histology (Stratified summary algorithm)

In [34]:
stratification_column = "HISTOLOGY"

# overall summary results
input_ = {
        "kwargs":{
            "columns": ["AGE"],
            "numeric_columns": ["AGE"],
            "stratification_column": stratification_column,
        }
    }

task = client.task.create(
    method="summary",
    
    organizations=[0],
    input_=input_
)

client.wait_for_results(task_id=task.get("id"))
result = client.result.from_task(task_id=task.get("id"))
result

info > Defining input parameters
info > Creating subtask for all organizations in the collaboration
info > Extracting payload from token
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Extracting payload from token
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Checking if data complies to privacy settings
info > Waiting for results
info > Mocking waiting for results
info > Results obtained!
info > Aggregating partial summaries
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
warn > node did not have results for a certain cohort
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
warn > node did not have results for a certain cohort
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
warn > node did not have results for a certain cohort
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
warn > node did not have results for a certain cohort
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
info > n num cols: 1
info > n means: 1
info > Aggregating partial summaries
warn > node did not have results for a certain cohort
info > n num cols: 1
info > n means: 1
info > {'columns': ['AGE']}
info > {'pelvis_cohort_HISTOLOGY==1013 Solitary fibrous tumour': [50.0], 'pelvis_cohort_HISTOLOGY==1010 Leiomyosarcoma': [49.42857142857143], 'pelvis_cohort_HISTOLOGY==1016 MPNST': [43.282051282051285], 'rps_pelvis_cohort_HISTOLOGY==1010 Leiomyosarcoma': [49.01190476190476], 'rps_cohort_HISTOLOGY==1022 Other sarcomas': [43.113207547169814], 'rps_pelvis_cohort_HISTOLOGY==1004/1007 Liposarcoma': [47.50588235294118], 'rps_pelvis_cohort_HISTOLOGY==1022 Other sarcomas': [44.25806451612903], 'pelvis_cohort_HISTOLOGY==1019 UPS': [45.926829268292686], 'rps_cohort_HISTOLOGY==1013 Solitary fibrous tumour': [41.87234042553192], 'rps_pelvis_cohort_HISTOLOGY==1019 UPS': [44.951219512195124], 'rps_cohort_HISTOLOGY==1019 UPS': [43.97560975609756], 'rps_cohort_HISTOLOGY==1016 MPNST': [49.38775510204081], 'pelvis_cohort_HISTOLOGY==1004/1007 Liposarcoma': [49.05681818181818], 'rps_cohort_HISTOLOGY==1010 Leiomyosarcoma': [48.595238095238095], 'rps_cohort_HISTOLOGY==1004/1007 Liposarcoma': [45.84146341463415], 'pelvis_cohort_HISTOLOGY==1022 Other sarcomas': [45.775], 'rps_pelvis_cohort_HISTOLOGY==1013 Solitary fibrous tumour': [45.397590361445786], 'rps_pelvis_cohort_HISTOLOGY==1016 MPNST': [46.68181818181818]}
info > Cake is a lie
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > {'rps_cohort': {'AGE': 292.8618725525099}, 'pelvis_cohort': {'AGE': 496.4898093359633}, 'rps_pelvis_cohort': {'AGE': 389.7440166493236}}
info > {'columns': ['AGE']}
info > {'pelvis_cohort_HISTOLOGY==1013 Solitary fibrous tumour': [50.0], 'pelvis_cohort_HISTOLOGY==1010 Leiomyosarcoma': [49.42857142857143], 'pelvis_cohort_HISTOLOGY==1016 MPNST': [43.282051282051285], 'rps_pelvis_cohort_HISTOLOGY==1010 Leiomyosarcoma': [49.01190476190476], 'rps_cohort_HISTOLOGY==1022 Other sarcomas': [43.113207547169814], 'rps_pelvis_cohort_HISTOLOGY==1004/1007 Liposarcoma': [47.50588235294118], 'rps_pelvis_cohort_HISTOLOGY==1022 Other sarcomas': [44.25806451612903], 'pelvis_cohort_HISTOLOGY==1019 UPS': [45.926829268292686], 'rps_cohort_HISTOLOGY==1013 Solitary fibrous tumour': [41.87234042553192], 'rps_pelvis_cohort_HISTOLOGY==1019 UPS': [44.951219512195124], 'rps_cohort_HISTOLOGY==1019 UPS': [43.97560975609756], 'rps_cohort_HISTOLOGY==1016 MPNST': [49.38775510204081], 'pelvis_cohort_HISTOLOGY==1004/1007 Liposarcoma': [49.05681818181818], 'rps_cohort_HISTOLOGY==1010 Leiomyosarcoma': [48.595238095238095], 'rps_cohort_HISTOLOGY==1004/1007 Liposarcoma': [45.84146341463415], 'pelvis_cohort_HISTOLOGY==1022 Other sarcomas': [45.775], 'rps_pelvis_cohort_HISTOLOGY==1013 Solitary fibrous tumour': [45.397590361445786], 'rps_pelvis_cohort_HISTOLOGY==1016 MPNST': [46.68181818181818]}
info > Cake is a lie
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > Checking if data complies to privacy settings
info > Calculating variance
info > {'rps_cohort': {'AGE': 12981.234042553191}, 'pelvis_cohort': {'AGE': 9014.78048780488}, 'rps_pelvis_cohort': {'AGE': 22350.804325736684}}
info > Hello!
info > Mocking waiting for results
info > Goodbye!
info > Mocking waiting for results

[{'pelvis_cohort_HISTOLOGY==1013 Solitary fibrous tumour': {'numeric': {'AGE': {'count': 36.0,
     'min': 20.0,
     'max': 75.0,
     'missing': 0.0,
     'sum': 1800.0,
     'median': {'mock-1': 51.0},
     'q_25': {'mock-1': 36.5},
     'q_75': {'mock-1': 61.75},
     'mean': 50.0,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 34},
   'counts_unique_values': {},
   'organization_id': 1},
  'pelvis_cohort_HISTOLOGY==1010 Leiomyosarcoma': {'numeric': {'AGE': {'count': 42.0,
     'min': 21.0,
     'max': 74.0,
     'missing': 0.0,
     'sum': 2076.0,
     'median': {'mock-1': 44.0},
     'q_25': {'mock-1': 37.5},
     'q_75': {'mock-1': 64.5},
     'mean': 49.42857142857143,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 39},
   'counts_unique_values': {},
   'organization_id': 1},
  'pelvis_cohort_HISTOLOGY==1016 MPNST': {'numeric': {'AGE': {'count': 39.0,
     'min': 18.0,
     'max': 75.0,
     'missing': 0.0,
     'sum': 1688.0,
     'median': {'mock-1': 41.0},
     'q_25': {'mock-1': 29.25},
     'q_75': {'mock-1': 61.25},
     'mean': 43.282051282051285,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 38},
   'counts_unique_values': {},
   'organization_id': 1},
  'rps_pelvis_cohort_HISTOLOGY==1010 Leiomyosarcoma': {'numeric': {'AGE': {'count': 84.0,
     'min': 18.0,
     'max': 75.0,
     'missing': 0.0,
     'sum': 4117.0,
     'median': {'mock-1': 47.0},
     'q_25': {'mock-1': 37.0},
     'q_75': {'mock-1': 63.0},
     'mean': 49.01190476190476,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 82},
   'counts_unique_values': {},
   'organization_id': 1},
  'rps_cohort_HISTOLOGY==1022 Other sarcomas': {'numeric': {'AGE': {'count': 53.0,
     'min': 18.0,
     'max': 75.0,
     'missing': 0.0,
     'sum': 2285.0,
     'median': {'mock-1': 45.0},
     'q_25': {'mock-1': 32.0},
     'q_75': {'mock-1': 54.0},
     'mean': 43.113207547169814,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 52},
   'counts_unique_values': {},
   'organization_id': 1},
  'rps_pelvis_cohort_HISTOLOGY==1004/1007 Liposarcoma': {'numeric': {'AGE': {'count': 170.0,
     'min': 18.0,
     'max': 75.0,
     'missing': 0.0,
     'sum': 8076.0,
     'median': {'mock-1': 47.0},
     'q_25': {'mock-1': 32.0},
     'q_75': {'mock-1': 62.0},
     'mean': 47.50588235294118,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 165},
   'counts_unique_values': {},
   'organization_id': 1},
  'rps_pelvis_cohort_HISTOLOGY==1022 Other sarcomas': {'numeric': {'AGE': {'count': 93.0,
     'min': 18.0,
     'max': 75.0,
     'missing': 0.0,
     'sum': 4116.0,
     'median': {'mock-1': 44.5},
     'q_25': {'mock-1': 33.0},
     'q_75': {'mock-1': 54.0},
     'mean': 44.25806451612903,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 92},
   'counts_unique_values': {},
   'organization_id': 1},
  'pelvis_cohort_HISTOLOGY==1019 UPS': {'numeric': {'AGE': {'count': 41.0,
     'min': 19.0,
     'max': 69.0,
     'missing': 0.0,
     'sum': 1883.0,
     'median': {'mock-1': 48.0},
     'q_25': {'mock-1': 32.0},
     'q_75': {'mock-1': 59.0},
     'mean': 45.926829268292686,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 41},
   'counts_unique_values': {},
   'organization_id': 1},
  'rps_cohort_HISTOLOGY==1013 Solitary fibrous tumour': {'numeric': {'AGE': {'count': 47.0,
     'min': 18.0,
     'max': 74.0,
     'missing': 0.0,
     'sum': 1968.0,
     'median': {'mock-1': 41.0},
     'q_25': {'mock-1': 26.0},
     'q_75': {'mock-1': 57.0},
     'mean': 41.87234042553192,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 47},
   'counts_unique_values': {},
   'organization_id': 1},
  'rps_pelvis_cohort_HISTOLOGY==1019 UPS': {'numeric': {'AGE': {'count': 82.0,
     'min': 19.0,
     'max': 75.0,
     'missing': 0.0,
     'sum': 3686.0,
     'median': {'mock-1': 43.0},
     'q_25': {'mock-1': 31.0},
     'q_75': {'mock-1': 59.75},
     'mean': 44.951219512195124,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 82},
   'counts_unique_values': {},
   'organization_id': 1},
  'rps_cohort_HISTOLOGY==1019 UPS': {'numeric': {'AGE': {'count': 41.0,
     'min': 19.0,
     'max': 75.0,
     'missing': 0.0,
     'sum': 1803.0,
     'median': {'mock-1': 40.0},
     'q_25': {'mock-1': 30.0},
     'q_75': {'mock-1': 60.0},
     'mean': 43.97560975609756,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 41},
   'counts_unique_values': {},
   'organization_id': 1},
  'rps_cohort_HISTOLOGY==1016 MPNST': {'numeric': {'AGE': {'count': 49.0,
     'min': 18.0,
     'max': 75.0,
     'missing': 0.0,
     'sum': 2420.0,
     'median': {'mock-1': 51.0},
     'q_25': {'mock-1': 35.75},
     'q_75': {'mock-1': 64.0},
     'mean': 49.38775510204081,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 48},
   'counts_unique_values': {},
   'organization_id': 1},
  'pelvis_cohort_HISTOLOGY==1004/1007 Liposarcoma': {'numeric': {'AGE': {'count': 88.0,
     'min': 18.0,
     'max': 75.0,
     'missing': 0.0,
     'sum': 4317.0,
     'median': {'mock-1': 47.0},
     'q_25': {'mock-1': 36.0},
     'q_75': {'mock-1': 63.0},
     'mean': 49.05681818181818,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 85},
   'counts_unique_values': {},
   'organization_id': 1},
  'rps_cohort_HISTOLOGY==1010 Leiomyosarcoma': {'numeric': {'AGE': {'count': 42.0,
     'min': 18.0,
     'max': 75.0,
     'missing': 0.0,
     'sum': 2041.0,
     'median': {'mock-1': 48.0},
     'q_25': {'mock-1': 37.0},
     'q_75': {'mock-1': 62.0},
     'mean': 48.595238095238095,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 41},
   'counts_unique_values': {},
   'organization_id': 1},
  'rps_cohort_HISTOLOGY==1004/1007 Liposarcoma': {'numeric': {'AGE': {'count': 82.0,
     'min': 18.0,
     'max': 75.0,
     'missing': 0.0,
     'sum': 3759.0,
     'median': {'mock-1': 46.0},
     'q_25': {'mock-1': 31.0},
     'q_75': {'mock-1': 59.5},
     'mean': 45.84146341463415,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 75},
   'counts_unique_values': {},
   'organization_id': 1},
  'pelvis_cohort_HISTOLOGY==1022 Other sarcomas': {'numeric': {'AGE': {'count': 40.0,
     'min': 19.0,
     'max': 72.0,
     'missing': 0.0,
     'sum': 1831.0,
     'median': {'mock-1': 44.0},
     'q_25': {'mock-1': 36.5},
     'q_75': {'mock-1': 54.5},
     'mean': 45.775,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 39},
   'counts_unique_values': {},
   'organization_id': 1},
  'rps_pelvis_cohort_HISTOLOGY==1013 Solitary fibrous tumour': {'numeric': {'AGE': {'count': 83.0,
     'min': 18.0,
     'max': 75.0,
     'missing': 0.0,
     'sum': 3768.0,
     'median': {'mock-1': 43.0},
     'q_25': {'mock-1': 29.0},
     'q_75': {'mock-1': 59.0},
     'mean': 45.397590361445786,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 81},
   'counts_unique_values': {},
   'organization_id': 1},
  'rps_pelvis_cohort_HISTOLOGY==1016 MPNST': {'numeric': {'AGE': {'count': 88.0,
     'min': 18.0,
     'max': 75.0,
     'missing': 0.0,
     'sum': 4108.0,
     'median': {'mock-1': 48.0},
     'q_25': {'mock-1': 33.0},
     'q_75': {'mock-1': 63.25},
     'mean': 46.68181818181818,
     'std': 0.0}},
   'categorical': {},
   'num_complete_rows_per_node': {'mock-1': 88},
   'counts_unique_values': {},
   'organization_id': 1}}]

In [38]:
result

{'pelvis_cohort_HISTOLOGY==1013 Solitary fibrous tumour': {'numeric': {'AGE': {'count': 36.0,
    'min': 20.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 1800.0,
    'median': {'mock-1': 51.0},
    'q_25': {'mock-1': 36.5},
    'q_75': {'mock-1': 61.75},
    'mean': 50.0,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 34},
  'counts_unique_values': {},
  'organization_id': 1},
 'pelvis_cohort_HISTOLOGY==1010 Leiomyosarcoma': {'numeric': {'AGE': {'count': 42.0,
    'min': 21.0,
    'max': 74.0,
    'missing': 0.0,
    'sum': 2076.0,
    'median': {'mock-1': 44.0},
    'q_25': {'mock-1': 37.5},
    'q_75': {'mock-1': 64.5},
    'mean': 49.42857142857143,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 39},
  'counts_unique_values': {},
  'organization_id': 1},
 'pelvis_cohort_HISTOLOGY==1016 MPNST': {'numeric': {'AGE': {'count': 39.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 1688.0,
    'median': {'mock-1': 41.0},
    'q_25': {'mock-1': 29.25},
    'q_75': {'mock-1': 61.25},
    'mean': 43.282051282051285,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 38},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_pelvis_cohort_HISTOLOGY==1010 Leiomyosarcoma': {'numeric': {'AGE': {'count': 84.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 4117.0,
    'median': {'mock-1': 47.0},
    'q_25': {'mock-1': 37.0},
    'q_75': {'mock-1': 63.0},
    'mean': 49.01190476190476,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 82},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_cohort_HISTOLOGY==1022 Other sarcomas': {'numeric': {'AGE': {'count': 53.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 2285.0,
    'median': {'mock-1': 45.0},
    'q_25': {'mock-1': 32.0},
    'q_75': {'mock-1': 54.0},
    'mean': 43.113207547169814,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 52},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_pelvis_cohort_HISTOLOGY==1004/1007 Liposarcoma': {'numeric': {'AGE': {'count': 170.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 8076.0,
    'median': {'mock-1': 47.0},
    'q_25': {'mock-1': 32.0},
    'q_75': {'mock-1': 62.0},
    'mean': 47.50588235294118,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 165},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_pelvis_cohort_HISTOLOGY==1022 Other sarcomas': {'numeric': {'AGE': {'count': 93.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 4116.0,
    'median': {'mock-1': 44.5},
    'q_25': {'mock-1': 33.0},
    'q_75': {'mock-1': 54.0},
    'mean': 44.25806451612903,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 92},
  'counts_unique_values': {},
  'organization_id': 1},
 'pelvis_cohort_HISTOLOGY==1019 UPS': {'numeric': {'AGE': {'count': 41.0,
    'min': 19.0,
    'max': 69.0,
    'missing': 0.0,
    'sum': 1883.0,
    'median': {'mock-1': 48.0},
    'q_25': {'mock-1': 32.0},
    'q_75': {'mock-1': 59.0},
    'mean': 45.926829268292686,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 41},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_cohort_HISTOLOGY==1013 Solitary fibrous tumour': {'numeric': {'AGE': {'count': 47.0,
    'min': 18.0,
    'max': 74.0,
    'missing': 0.0,
    'sum': 1968.0,
    'median': {'mock-1': 41.0},
    'q_25': {'mock-1': 26.0},
    'q_75': {'mock-1': 57.0},
    'mean': 41.87234042553192,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 47},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_pelvis_cohort_HISTOLOGY==1019 UPS': {'numeric': {'AGE': {'count': 82.0,
    'min': 19.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 3686.0,
    'median': {'mock-1': 43.0},
    'q_25': {'mock-1': 31.0},
    'q_75': {'mock-1': 59.75},
    'mean': 44.951219512195124,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 82},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_cohort_HISTOLOGY==1019 UPS': {'numeric': {'AGE': {'count': 41.0,
    'min': 19.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 1803.0,
    'median': {'mock-1': 40.0},
    'q_25': {'mock-1': 30.0},
    'q_75': {'mock-1': 60.0},
    'mean': 43.97560975609756,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 41},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_cohort_HISTOLOGY==1016 MPNST': {'numeric': {'AGE': {'count': 49.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 2420.0,
    'median': {'mock-1': 51.0},
    'q_25': {'mock-1': 35.75},
    'q_75': {'mock-1': 64.0},
    'mean': 49.38775510204081,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 48},
  'counts_unique_values': {},
  'organization_id': 1},
 'pelvis_cohort_HISTOLOGY==1004/1007 Liposarcoma': {'numeric': {'AGE': {'count': 88.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 4317.0,
    'median': {'mock-1': 47.0},
    'q_25': {'mock-1': 36.0},
    'q_75': {'mock-1': 63.0},
    'mean': 49.05681818181818,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 85},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_cohort_HISTOLOGY==1010 Leiomyosarcoma': {'numeric': {'AGE': {'count': 42.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 2041.0,
    'median': {'mock-1': 48.0},
    'q_25': {'mock-1': 37.0},
    'q_75': {'mock-1': 62.0},
    'mean': 48.595238095238095,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 41},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_cohort_HISTOLOGY==1004/1007 Liposarcoma': {'numeric': {'AGE': {'count': 82.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 3759.0,
    'median': {'mock-1': 46.0},
    'q_25': {'mock-1': 31.0},
    'q_75': {'mock-1': 59.5},
    'mean': 45.84146341463415,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 75},
  'counts_unique_values': {},
  'organization_id': 1},
 'pelvis_cohort_HISTOLOGY==1022 Other sarcomas': {'numeric': {'AGE': {'count': 40.0,
    'min': 19.0,
    'max': 72.0,
    'missing': 0.0,
    'sum': 1831.0,
    'median': {'mock-1': 44.0},
    'q_25': {'mock-1': 36.5},
    'q_75': {'mock-1': 54.5},
    'mean': 45.775,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 39},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_pelvis_cohort_HISTOLOGY==1013 Solitary fibrous tumour': {'numeric': {'AGE': {'count': 83.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 3768.0,
    'median': {'mock-1': 43.0},
    'q_25': {'mock-1': 29.0},
    'q_75': {'mock-1': 59.0},
    'mean': 45.397590361445786,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 81},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_pelvis_cohort_HISTOLOGY==1016 MPNST': {'numeric': {'AGE': {'count': 88.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 4108.0,
    'median': {'mock-1': 48.0},
    'q_25': {'mock-1': 33.0},
    'q_75': {'mock-1': 63.25},
    'mean': 46.68181818181818,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 88},
  'counts_unique_values': {},
  'organization_id': 1}}

{'pelvis_cohort_HISTOLOGY==1013 Solitary fibrous tumour': {'numeric': {'AGE': {'count': 36.0,
    'min': 20.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 1800.0,
    'median': {'mock-1': 51.0},
    'q_25': {'mock-1': 36.5},
    'q_75': {'mock-1': 61.75},
    'mean': 50.0,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 34},
  'counts_unique_values': {},
  'organization_id': 1},
 'pelvis_cohort_HISTOLOGY==1010 Leiomyosarcoma': {'numeric': {'AGE': {'count': 42.0,
    'min': 21.0,
    'max': 74.0,
    'missing': 0.0,
    'sum': 2076.0,
    'median': {'mock-1': 44.0},
    'q_25': {'mock-1': 37.5},
    'q_75': {'mock-1': 64.5},
    'mean': 49.42857142857143,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 39},
  'counts_unique_values': {},
  'organization_id': 1},
 'pelvis_cohort_HISTOLOGY==1016 MPNST': {'numeric': {'AGE': {'count': 39.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 1688.0,
    'median': {'mock-1': 41.0},
    'q_25': {'mock-1': 29.25},
    'q_75': {'mock-1': 61.25},
    'mean': 43.282051282051285,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 38},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_pelvis_cohort_HISTOLOGY==1010 Leiomyosarcoma': {'numeric': {'AGE': {'count': 84.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 4117.0,
    'median': {'mock-1': 47.0},
    'q_25': {'mock-1': 37.0},
    'q_75': {'mock-1': 63.0},
    'mean': 49.01190476190476,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 82},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_cohort_HISTOLOGY==1022 Other sarcomas': {'numeric': {'AGE': {'count': 53.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 2285.0,
    'median': {'mock-1': 45.0},
    'q_25': {'mock-1': 32.0},
    'q_75': {'mock-1': 54.0},
    'mean': 43.113207547169814,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 52},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_pelvis_cohort_HISTOLOGY==1004/1007 Liposarcoma': {'numeric': {'AGE': {'count': 170.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 8076.0,
    'median': {'mock-1': 47.0},
    'q_25': {'mock-1': 32.0},
    'q_75': {'mock-1': 62.0},
    'mean': 47.50588235294118,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 165},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_pelvis_cohort_HISTOLOGY==1022 Other sarcomas': {'numeric': {'AGE': {'count': 93.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 4116.0,
    'median': {'mock-1': 44.5},
    'q_25': {'mock-1': 33.0},
    'q_75': {'mock-1': 54.0},
    'mean': 44.25806451612903,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 92},
  'counts_unique_values': {},
  'organization_id': 1},
 'pelvis_cohort_HISTOLOGY==1019 UPS': {'numeric': {'AGE': {'count': 41.0,
    'min': 19.0,
    'max': 69.0,
    'missing': 0.0,
    'sum': 1883.0,
    'median': {'mock-1': 48.0},
    'q_25': {'mock-1': 32.0},
    'q_75': {'mock-1': 59.0},
    'mean': 45.926829268292686,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 41},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_cohort_HISTOLOGY==1013 Solitary fibrous tumour': {'numeric': {'AGE': {'count': 47.0,
    'min': 18.0,
    'max': 74.0,
    'missing': 0.0,
    'sum': 1968.0,
    'median': {'mock-1': 41.0},
    'q_25': {'mock-1': 26.0},
    'q_75': {'mock-1': 57.0},
    'mean': 41.87234042553192,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 47},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_pelvis_cohort_HISTOLOGY==1019 UPS': {'numeric': {'AGE': {'count': 82.0,
    'min': 19.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 3686.0,
    'median': {'mock-1': 43.0},
    'q_25': {'mock-1': 31.0},
    'q_75': {'mock-1': 59.75},
    'mean': 44.951219512195124,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 82},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_cohort_HISTOLOGY==1019 UPS': {'numeric': {'AGE': {'count': 41.0,
    'min': 19.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 1803.0,
    'median': {'mock-1': 40.0},
    'q_25': {'mock-1': 30.0},
    'q_75': {'mock-1': 60.0},
    'mean': 43.97560975609756,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 41},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_cohort_HISTOLOGY==1016 MPNST': {'numeric': {'AGE': {'count': 49.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 2420.0,
    'median': {'mock-1': 51.0},
    'q_25': {'mock-1': 35.75},
    'q_75': {'mock-1': 64.0},
    'mean': 49.38775510204081,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 48},
  'counts_unique_values': {},
  'organization_id': 1},
 'pelvis_cohort_HISTOLOGY==1004/1007 Liposarcoma': {'numeric': {'AGE': {'count': 88.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 4317.0,
    'median': {'mock-1': 47.0},
    'q_25': {'mock-1': 36.0},
    'q_75': {'mock-1': 63.0},
    'mean': 49.05681818181818,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 85},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_cohort_HISTOLOGY==1010 Leiomyosarcoma': {'numeric': {'AGE': {'count': 42.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 2041.0,
    'median': {'mock-1': 48.0},
    'q_25': {'mock-1': 37.0},
    'q_75': {'mock-1': 62.0},
    'mean': 48.595238095238095,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 41},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_cohort_HISTOLOGY==1004/1007 Liposarcoma': {'numeric': {'AGE': {'count': 82.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 3759.0,
    'median': {'mock-1': 46.0},
    'q_25': {'mock-1': 31.0},
    'q_75': {'mock-1': 59.5},
    'mean': 45.84146341463415,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 75},
  'counts_unique_values': {},
  'organization_id': 1},
 'pelvis_cohort_HISTOLOGY==1022 Other sarcomas': {'numeric': {'AGE': {'count': 40.0,
    'min': 19.0,
    'max': 72.0,
    'missing': 0.0,
    'sum': 1831.0,
    'median': {'mock-1': 44.0},
    'q_25': {'mock-1': 36.5},
    'q_75': {'mock-1': 54.5},
    'mean': 45.775,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 39},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_pelvis_cohort_HISTOLOGY==1013 Solitary fibrous tumour': {'numeric': {'AGE': {'count': 83.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 3768.0,
    'median': {'mock-1': 43.0},
    'q_25': {'mock-1': 29.0},
    'q_75': {'mock-1': 59.0},
    'mean': 45.397590361445786,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 81},
  'counts_unique_values': {},
  'organization_id': 1},
 'rps_pelvis_cohort_HISTOLOGY==1016 MPNST': {'numeric': {'AGE': {'count': 88.0,
    'min': 18.0,
    'max': 75.0,
    'missing': 0.0,
    'sum': 4108.0,
    'median': {'mock-1': 48.0},
    'q_25': {'mock-1': 33.0},
    'q_75': {'mock-1': 63.25},
    'mean': 46.68181818181818,
    'std': 0.0}},
  'categorical': {},
  'num_complete_rows_per_node': {'mock-1': 88},
  'counts_unique_values': {},
  'organization_id': 1}}

In [47]:
cohort_key = cohort_keys[0]
cohort_key

'rps_pelvis_cohort_HISTOLOGY==1010 Leiomyosarcoma'

In [55]:
categories

['1022 Other sarcomas',
 '1010 Leiomyosarcoma',
 '1004/1007 Liposarcoma',
 '1016 MPNST',
 '1019 UPS',
 '1013 Solitary fibrous tumour']

In [ ]:
# stratification_column="HISTOLOGY"

# Handle list-of-dict input
if isinstance(result, list) and isinstance(result[0], dict):
    result = result[0]

if not isinstance(result, dict):
    raise ValueError("Expected 'result' to be a dict or a list containing one dict")

cohorts, categories = map(list, map(set, zip(*(key.split(f'_{stratification_column}==') for key in result.keys()))))

for cohort_name in cohorts:

    cohort_keys = [key for key in result.keys() if key.startswith(cohort_name)]

    df = pd.DataFrame()

    for category in categories:
        cohort_key = f"{cohort_name}_{stratification_column}=={category}"
        vars = list(result[cohort_key]['numeric'].keys())

        for var in vars:
            stats = result[cohort_key]['numeric'][var]
            row = {
                f'{stratification_column.title()}': category,
                'Mean': round(stats['mean'], 1),
                'SD': round(stats['std'], 1),
                'Min': int(stats['min']),
                'Max': int(stats['max']),
                'Count': int(stats['count']),
                'Missing': int(stats['missing'])
            }
            df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
    
            # --- MultiIndex for display ---


df

#TODO: n= toevoegen count / missing
#TODO: percentages count / missing

                      Histology  Mean   SD  Min  Max  Count  Missing
0           1022 Other sarcomas  44.3  0.0   18   75     93        0
1           1010 Leiomyosarcoma  49.0  0.0   18   75     84        0
2         1004/1007 Liposarcoma  47.5  0.0   18   75    170        0
3                    1016 MPNST  46.7  0.0   18   75     88        0
4                      1019 UPS  45.0  0.0   19   75     82        0
5  1013 Solitary fibrous tumour  45.4  0.0   18   75     83        0

In [64]:
import pandas as pd

# stratification_column="HISTOLOGY"

# Handle list-of-dict input
if isinstance(result, list) and isinstance(result[0], dict):
    result = result[0]

if not isinstance(result, dict):
    raise ValueError("Expected 'result' to be a dict or a list containing one dict")

cohorts, categories = map(list, map(set, zip(*(key.split(f'_{stratification_column}==') for key in result.keys()))))
categories = sorted(categories)

for cohort_name in cohorts:
    print(f"Cohort: {cohort_name}")

    cohort_keys = [key for key in result.keys() if key.startswith(cohort_name)]

    df_dict = {}  # We'll build a dict of dicts for MultiIndex

    for category in categories:
        cohort_key = f"{cohort_name}_{stratification_column}=={category}"
        vars = list(result[cohort_key]['numeric'].keys())

        row_dict = {}
        for var in vars:
            stats = result[cohort_key]['numeric'][var]
            # For each stat, we add a tuple key: (variable_name, stat_name)
            row_dict.update({
                (var, 'Mean'): round(stats['mean'], 1),
                (var, 'SD'): round(stats['std'], 1),
                (var, 'Min'): int(stats['min']),
                (var, 'Max'): int(stats['max']),
                (var, 'Count'): int(stats['count']),
                (var, 'Missing'): int(stats['missing'])
            })

        # Add the stratification column separately
        row_dict = {(stratification_column.title(), ''): category, **row_dict}
        df_dict[category] = row_dict

    # Create DataFrame with MultiIndex columns
    df = pd.DataFrame.from_dict(df_dict, orient='index')
    df.columns = pd.MultiIndex.from_tuples(df.columns)
    df.reset_index(drop=True, inplace=True)

    display(df)

Cohort: rps_cohort

                      Histology   AGE
                                 Mean   SD Min Max Count Missing
0         1004/1007 Liposarcoma  45.8  0.0  18  75    82       0
1           1010 Leiomyosarcoma  48.6  0.0  18  75    42       0
2  1013 Solitary fibrous tumour  41.9  0.0  18  74    47       0
3                    1016 MPNST  49.4  0.0  18  75    49       0
4                      1019 UPS  44.0  0.0  19  75    41       0
5           1022 Other sarcomas  43.1  0.0  18  75    53       0

Cohort: pelvis_cohort

                      Histology   AGE
                                 Mean   SD Min Max Count Missing
0         1004/1007 Liposarcoma  49.1  0.0  18  75    88       0
1           1010 Leiomyosarcoma  49.4  0.0  21  74    42       0
2  1013 Solitary fibrous tumour  50.0  0.0  20  75    36       0
3                    1016 MPNST  43.3  0.0  18  75    39       0
4                      1019 UPS  45.9  0.0  19  69    41       0
5           1022 Other sarcomas  45.8  0.0  19  72    40       0

Cohort: rps_pelvis_cohort

                      Histology   AGE
                                 Mean   SD Min Max Count Missing
0         1004/1007 Liposarcoma  47.5  0.0  18  75   170       0
1           1010 Leiomyosarcoma  49.0  0.0  18  75    84       0
2  1013 Solitary fibrous tumour  45.4  0.0  18  75    83       0
3                    1016 MPNST  46.7  0.0  18  75    88       0
4                      1019 UPS  45.0  0.0  19  75    82       0
5           1022 Other sarcomas  44.3  0.0  18  75    93       0

In [24]:
#TODO: Viz table maken

### 2b. Histology vs FNCLCC Grade (Cross tabulation algorithm)

#### Send crosstab task

In [ ]:
# crosstab
input_ = {
        "kwargs":{
            "results_col": "FNCLCC_GRADE",
            "group_cols": ["HISTOLOGY"],
            "organizations_to_include": [0,1],
        }
    }

task = client.task.create(
    method="crosstab",
    organizations=[0],
    input_=input_
)

client.wait_for_results(task_id=task.get("id"))
result = client.result.from_task(task_id=task.get("id"))
result

#### Viz function

In [91]:
import pandas as pd
import numpy as np

def visualize_contingency(result, row_var, col_var, percentage_mode=None):
    """
    Visualize contingency tables from the given result structure with counts + percentages.

    Parameters
    ----------
    result : list or dict
        JSON-like structure containing cohort data.
    row_var : str
        Variable to use for rows (e.g., "FNCLCC_GRADE", "Sex").
    col_var : str
        Variable to use for columns (e.g., "Histology", "Tumor Rupture").
    percentage_mode: str, optional
        Mode for displaying percentages ("row", "column", "total").
    """

    # Handle list-of-dict input
    if isinstance(result, list) and isinstance(result[0], dict):
        result = result[0]

    if not isinstance(result, dict):
        raise ValueError("Expected 'result' to be a dict or a list containing one dict")

    for cohort_name, cohort_data in result.items():
        contingency = cohort_data.get("contingency_table", [])
        if not contingency:
            print(f"⚠️ No contingency table found for {cohort_name}")
            continue

        df = pd.DataFrame(contingency)

        # Identify row column
        row_col_name = None
        for c in df.columns:
            if row_var.lower() in c.lower():
                row_col_name = c
                break
        if row_col_name is None:
            print(f"⚠️ Could not find column for '{row_var}' in {cohort_name}")
            continue

        df.rename(columns={row_col_name: row_var.replace("_", " ").title()}, inplace=True)
        row_col_name = row_var.replace("_", " ").title()

        # Convert numeric columns safely
        for c in df.columns:
            if c != row_col_name:
                df[c] = pd.to_numeric(df[c], errors="coerce").fillna(0)

        # Sort columns (alphabetical except 'N/A' and 'Total' at end)
        cols = sorted([c for c in df.columns if c not in [row_col_name, 'N/A', 'Total']])
        for special in ['N/A', 'Total']:
            if special in df.columns:
                cols.append(special)
        df = df[[row_col_name] + cols]

        # --- Percentage computation ---
        if percentage_mode is not None:
            numeric_cols = [c for c in df.columns if c != row_col_name]
            df_pct = pd.DataFrame(index=df.index, columns=numeric_cols, dtype=float)

            total_row_mask = df[row_col_name].astype(str).str.lower() == "total"
            data_rows_mask = ~total_row_mask

            for col in numeric_cols:
                if percentage_mode == "row":
                    for idx in df.index:
                        row_total = df.loc[idx, "Total"] if "Total" in df.columns else np.nan
                        if col == "Total":
                            df_pct.loc[idx, col] = 100
                        else:
                            df_pct.loc[idx, col] = df.loc[idx, col] / row_total * 100 if pd.notna(row_total) and row_total > 0 else 0

                elif percentage_mode == "column":
                    # Column total excluding Total row
                    col_total = df.loc[data_rows_mask, col].sum()
                    for idx in df.index:
                        if total_row_mask.loc[idx]:
                            df_pct.loc[idx, col] = np.nan
                        else:
                            df_pct.loc[idx, col] = df.loc[idx, col] / col_total * 100 if col_total > 0 else 0
                    # Total row percentage = 100%
                    if total_row_mask.any():
                        df_pct.loc[total_row_mask, col] = 100.0

                elif percentage_mode == "total":
                    # Grand total excluding Total row/col
                    grand_total = df.loc[data_rows_mask, [c for c in df.columns if c != row_col_name and c != "Total"]].to_numpy().sum()
                    for idx in df.index:
                        df_pct.loc[idx, col] = df.loc[idx, col] / grand_total * 100 if grand_total > 0 else 0

                else:
                    raise ValueError("percentage_mode must be 'row', 'column', or 'total'")

            # --- Combine counts + percentages ---
            df_pct = df_pct.fillna(0)
            for col in numeric_cols:
                df[col] = df[col].astype(int).astype(str) + " (" + df_pct[col].round(1).astype(str) + "%)"

        # --- MultiIndex for display ---
        multi_cols = [(col_var.replace("_", " ").title(), c) if c not in [row_col_name, "Total"]
                      else ("", c) for c in df.columns]
        df.columns = pd.MultiIndex.from_tuples(multi_cols)

        # --- Styling ---
        is_sub = df[("", row_col_name)].astype(str).str.lower().str.startswith("grade")

        def style_rows(row):
            if not is_sub.loc[row.name]:
                return ["font-weight: normal; background-color: #f2f2f2"] * len(row)
            else:
                return ["padding-left: 20px"] + [""] * (len(row) - 1)

        styled_df = (
            df.style
            .apply(style_rows, axis=1)
            .hide(axis="index")
            .set_properties(subset=[("", row_col_name)], **{"text-align": "left"})
            .set_table_styles([
                {"selector": "th", "props": [
                    ("font-weight", "bold"),
                    ("background-color", "#d9d9d9"),
                    ("text-align", "center")
                ]}
            ])
        )

        # --- Chi-square stats ---
        chi2 = cohort_data.get("chi2", {}).get("chi2")
        pval = cohort_data.get("chi2", {}).get("P-value")

        print(f"\n--- {cohort_name.replace('_', ' ').title()} ---")
        if chi2 and pval:
            print(f"Chi² = {float(chi2):.3f},  p = {float(pval):.3f}")
        if percentage_mode:
            print(f"Percentage mode: {percentage_mode.title()}")

        display(styled_df)

#### Contingency table (percentage_mode = row)

In [93]:
visualize_contingency(result, row_var="HISTOLOGY", col_var="FNCLCC_GRADE", percentage_mode="row")

--- Rps Cohort ---
Chi² = 20.214,  p = 0.164
Percentage mode: Row

--- Pelvis Cohort ---
Chi² = 8.348,  p = 0.909
Percentage mode: Row

--- Rps Pelvis Cohort ---
Chi² = 12.286,  p = 0.657
Percentage mode: Row

#### Contingency table (percentage_mode = column)

In [94]:
visualize_contingency(result, row_var="HISTOLOGY", col_var="FNCLCC_GRADE", percentage_mode="column")

--- Rps Cohort ---
Chi² = 20.214,  p = 0.164
Percentage mode: Column

--- Pelvis Cohort ---
Chi² = 8.348,  p = 0.909
Percentage mode: Column

--- Rps Pelvis Cohort ---
Chi² = 12.286,  p = 0.657
Percentage mode: Column

#### Contingency table (percentage_mode = total)

In [95]:
visualize_contingency(result, row_var="HISTOLOGY", col_var="FNCLCC_GRADE", percentage_mode="total")

--- Rps Cohort ---
Chi² = 20.214,  p = 0.164
Percentage mode: Total

--- Pelvis Cohort ---
Chi² = 8.348,  p = 0.909
Percentage mode: Total

--- Rps Pelvis Cohort ---
Chi² = 12.286,  p = 0.657
Percentage mode: Total

### 2c. Histology vs Post-operative Radiotherapy (Cross tabulation algorithm)

#### Send crosstab task

In [105]:
# crosstab
input_ = {
        "kwargs":{
            "results_col": "POST_OPERATIVE_RADIO",
            "group_cols": ["HISTOLOGY"],
            "organizations_to_include": [0,1],
        }
    }

task = client.task.create(
    method="crosstab",
    organizations=[0],
    input_=input_
)

client.wait_for_results(task_id=task.get("id"))
result = client.result.from_task(task_id=task.get("id"))
result

info > Defining input parameters
info > Creating subtask to compute partial contingency tables
info > Checking privacy settings before starting...
info > Creating contingency table...
info > Contingency table created!
info > Checking if privacy threshold is met by any values...
info > Replacing values below threshold with privacy-enhancing values...
info > Returning results!
info > Checking privacy settings before starting...
info > Creating contingency table...
info > Contingency table created!
info > Checking if privacy threshold is met by any values...
info > Replacing values below threshold with privacy-enhancing values...
info > Returning results!
info > Checking privacy settings before starting...
info > Creating contingency table...
info > Contingency table created!
info > Checking if privacy threshold is met by any values...
info > Replacing values below threshold with privacy-enhancing values...
info > Returning results!
info > Checking privacy settings before starting...
info > Creating contingency table...
info > Contingency table created!
info > Checking if privacy threshold is met by any values...
info > Replacing values below threshold with privacy-enhancing values...
info > Returning results!
info > Checking privacy settings before starting...
info > Creating contingency table...
info > Contingency table created!
info > Checking if privacy threshold is met by any values...
info > Replacing values below threshold with privacy-enhancing values...
info > Returning results!
info > Checking privacy settings before starting...
info > Creating contingency table...
info > Contingency table created!
info > Checking if privacy threshold is met by any values...
info > Replacing values below threshold with privacy-enhancing values...
info > Returning results!
info > Waiting for results
info > Mocking waiting for results
info > Results obtained!
info > Computing chi-squared statistic...
info > Computing chi-squared statistic...
info > Computing chi-squared statistic...
info > Mocking waiting for results

[{'rps_cohort': {'contingency_table': [{'HISTOLOGY': '1004/1007 Liposarcoma',
     '1.0': '24',
     '0.0': '58',
     'Total': '82'},
    {'HISTOLOGY': '1010 Leiomyosarcoma',
     '1.0': '14',
     '0.0': '28',
     'Total': '42'},
    {'HISTOLOGY': '1013 Solitary fibrous tumour',
     '1.0': '11',
     '0.0': '36',
     'Total': '47'},
    {'HISTOLOGY': '1016 MPNST', '1.0': '8', '0.0': '41', 'Total': '49'},
    {'HISTOLOGY': '1019 UPS', '1.0': '12', '0.0': '29', 'Total': '41'},
    {'HISTOLOGY': '1022 Other sarcomas',
     '1.0': '16',
     '0.0': '37',
     'Total': '53'},
    {'HISTOLOGY': 'Total', '1.0': '85', '0.0': '229', 'Total': '314'}],
   'chi2': {'chi2': '4.581444886513365', 'P-value': '0.46906089214803726'}},
  'pelvis_cohort': {'contingency_table': [{'HISTOLOGY': '1004/1007 Liposarcoma',
     '1.0': '18',
     '0.0': '70',
     'Total': '88'},
    {'HISTOLOGY': '1010 Leiomyosarcoma',
     '1.0': '13',
     '0.0': '29',
     'Total': '42'},
    {'HISTOLOGY': '1013 Solitary fibrous tumour',
     '1.0': '8',
     '0.0': '28',
     'Total': '36'},
    {'HISTOLOGY': '1016 MPNST', '1.0': '13', '0.0': '26', 'Total': '39'},
    {'HISTOLOGY': '1019 UPS', '1.0': '7', '0.0': '34', 'Total': '41'},
    {'HISTOLOGY': '1022 Other sarcomas',
     '1.0': '7',
     '0.0': '33',
     'Total': '40'},
    {'HISTOLOGY': 'Total', '1.0': '66', '0.0': '220', 'Total': '286'}],
   'chi2': {'chi2': '5.667648992831919', 'P-value': '0.3399124620885317'}},
  'rps_pelvis_cohort': {'contingency_table': [{'HISTOLOGY': '1004/1007 Liposarcoma',
     '1.0': '42',
     '0.0': '128',
     'Total': '170'},
    {'HISTOLOGY': '1010 Leiomyosarcoma',
     '1.0': '27',
     '0.0': '57',
     'Total': '84'},
    {'HISTOLOGY': '1013 Solitary fibrous tumour',
     '1.0': '19',
     '0.0': '64',
     'Total': '83'},
    {'HISTOLOGY': '1016 MPNST', '1.0': '21', '0.0': '67', 'Total': '88'},
    {'HISTOLOGY': '1019 UPS', '1.0': '19', '0.0': '63', 'Total': '82'},
    {'HISTOLOGY': '1022 Other sarcomas',
     '1.0': '23',
     '0.0': '70',
     'Total': '93'},
    {'HISTOLOGY': 'Total', '1.0': '151', '0.0': '449', 'Total': '600'}],
   'chi2': {'chi2': '2.680115516981201', 'P-value': '0.7491579605308771'}}}]

#### Contingency table (percentage_mode = row)

In [106]:
visualize_contingency(result, row_var="HISTOLOGY", col_var="POST_OPERATIVE_RADIO", percentage_mode="row")

--- Rps Cohort ---
Chi² = 4.581,  p = 0.469
Percentage mode: Row

--- Pelvis Cohort ---
Chi² = 5.668,  p = 0.340
Percentage mode: Row

--- Rps Pelvis Cohort ---
Chi² = 2.680,  p = 0.749
Percentage mode: Row

#### Contingency table (percentage_mode = column)

In [107]:
visualize_contingency(result, row_var="HISTOLOGY", col_var="POST_OPERATIVE_RADIO", percentage_mode="column")

--- Rps Cohort ---
Chi² = 4.581,  p = 0.469
Percentage mode: Column

--- Pelvis Cohort ---
Chi² = 5.668,  p = 0.340
Percentage mode: Column

--- Rps Pelvis Cohort ---
Chi² = 2.680,  p = 0.749
Percentage mode: Column

#### Contingency table (percentage_mode = total)

In [108]:
visualize_contingency(result, row_var="HISTOLOGY", col_var="POST_OPERATIVE_RADIO", percentage_mode="total")

--- Rps Cohort ---
Chi² = 4.581,  p = 0.469
Percentage mode: Total

--- Pelvis Cohort ---
Chi² = 5.668,  p = 0.340
Percentage mode: Total

--- Rps Pelvis Cohort ---
Chi² = 2.680,  p = 0.749
Percentage mode: Total

## 3. Across center differences
( xxx algorithm)
(link)

### 3a. Categorical variables: Chi-squared

#### Send crosstab task

In [ ]:
#TODO: only pass relevant variables?
#TODO: some variables now are missing (0.0/1.0)
# crosstab
input_ = {
        "kwargs":{
            "organizations_to_include": [0,1],
        }
    }

task = client.task.create(
    method="crosstab_centers",
    organizations=[0],
    input_=input_
)

client.wait_for_results(task_id=task.get("id"))
result = client.result.from_task(task_id=task.get("id"))
result

info > Extracting payload from token
info > Extracting payload from token
info > Mocking waiting for results
info > Mocking waiting for results

[[{'Cohort': {'24': 'pelvis_cohort',
    '23': 'pelvis_cohort',
    '40': 'pelvis_cohort',
    '41': 'pelvis_cohort',
    '39': 'pelvis_cohort',
    '36': 'pelvis_cohort',
    '33': 'pelvis_cohort',
    '34': 'pelvis_cohort',
    '35': 'pelvis_cohort',
    '27': 'pelvis_cohort',
    '32': 'pelvis_cohort',
    '29': 'pelvis_cohort',
    '31': 'pelvis_cohort',
    '30': 'pelvis_cohort',
    '28': 'pelvis_cohort',
    '37': 'pelvis_cohort',
    '38': 'pelvis_cohort',
    '21': 'pelvis_cohort',
    '22': 'pelvis_cohort',
    '25': 'pelvis_cohort',
    '26': 'pelvis_cohort',
    '3': 'rps_cohort',
    '2': 'rps_cohort',
    '19': 'rps_cohort',
    '20': 'rps_cohort',
    '18': 'rps_cohort',
    '14': 'rps_cohort',
    '12': 'rps_cohort',
    '13': 'rps_cohort',
    '15': 'rps_cohort',
    '6': 'rps_cohort',
    '11': 'rps_cohort',
    '8': 'rps_cohort',
    '10': 'rps_cohort',
    '9': 'rps_cohort',
    '7': 'rps_cohort',
    '16': 'rps_cohort',
    '17': 'rps_cohort',
    '0': 'rps_cohort',
    '1': 'rps_cohort',
    '4': 'rps_cohort',
    '5': 'rps_cohort',
    '45': 'rps_pelvis_cohort',
    '44': 'rps_pelvis_cohort',
    '61': 'rps_pelvis_cohort',
    '62': 'rps_pelvis_cohort',
    '60': 'rps_pelvis_cohort',
    '57': 'rps_pelvis_cohort',
    '54': 'rps_pelvis_cohort',
    '55': 'rps_pelvis_cohort',
    '56': 'rps_pelvis_cohort',
    '48': 'rps_pelvis_cohort',
    '53': 'rps_pelvis_cohort',
    '50': 'rps_pelvis_cohort',
    '52': 'rps_pelvis_cohort',
    '51': 'rps_pelvis_cohort',
    '49': 'rps_pelvis_cohort',
    '58': 'rps_pelvis_cohort',
    '59': 'rps_pelvis_cohort',
    '42': 'rps_pelvis_cohort',
    '43': 'rps_pelvis_cohort',
    '46': 'rps_pelvis_cohort',
    '47': 'rps_pelvis_cohort'},
   'Variable': {'24': 'CENSOR',
    '23': 'CENSOR',
    '40': 'COMPLETENESS_OF_RESECTION',
    '41': 'COMPLETENESS_OF_RESECTION',
    '39': 'COMPLETENESS_OF_RESECTION',
    '36': 'FNCLCC_GRADE',
    '33': 'FNCLCC_GRADE',
    '34': 'FNCLCC_GRADE',
    '35': 'FNCLCC_GRADE',
    '27': 'HISTOLOGY',
    '32': 'HISTOLOGY',
    '29': 'HISTOLOGY',
    '31': 'HISTOLOGY',
    '30': 'HISTOLOGY',
    '28': 'HISTOLOGY',
    '37': 'MULTIFOCALITY',
    '38': 'MULTIFOCALITY',
    '21': 'SEX',
    '22': 'SEX',
    '25': 'STATUS',
    '26': 'STATUS',
    '3': 'CENSOR',
    '2': 'CENSOR',
    '19': 'COMPLETENESS_OF_RESECTION',
    '20': 'COMPLETENESS_OF_RESECTION',
    '18': 'COMPLETENESS_OF_RESECTION',
    '14': 'FNCLCC_GRADE',
    '12': 'FNCLCC_GRADE',
    '13': 'FNCLCC_GRADE',
    '15': 'FNCLCC_GRADE',
    '6': 'HISTOLOGY',
    '11': 'HISTOLOGY',
    '8': 'HISTOLOGY',
    '10': 'HISTOLOGY',
    '9': 'HISTOLOGY',
    '7': 'HISTOLOGY',
    '16': 'MULTIFOCALITY',
    '17': 'MULTIFOCALITY',
    '0': 'SEX',
    '1': 'SEX',
    '4': 'STATUS',
    '5': 'STATUS',
    '45': 'CENSOR',
    '44': 'CENSOR',
    '61': 'COMPLETENESS_OF_RESECTION',
    '62': 'COMPLETENESS_OF_RESECTION',
    '60': 'COMPLETENESS_OF_RESECTION',
    '57': 'FNCLCC_GRADE',
    '54': 'FNCLCC_GRADE',
    '55': 'FNCLCC_GRADE',
    '56': 'FNCLCC_GRADE',
    '48': 'HISTOLOGY',
    '53': 'HISTOLOGY',
    '50': 'HISTOLOGY',
    '52': 'HISTOLOGY',
    '51': 'HISTOLOGY',
    '49': 'HISTOLOGY',
    '58': 'MULTIFOCALITY',
    '59': 'MULTIFOCALITY',
    '42': 'SEX',
    '43': 'SEX',
    '46': 'STATUS',
    '47': 'STATUS'},
   'Level': {'24': '0',
    '23': '1',
    '40': 'Macroscopically complete',
    '41': 'Macroscopically incomplete',
    '39': 'N/A2',
    '36': 'Grade 1 tumor',
    '33': 'Grade 2 tumor',
    '34': 'Grade 3 tumor',
    '35': 'N/A',
    '27': '1004/1007 Liposarcoma',
    '32': '1010 Leiomyosarcoma',
    '29': '1013 Solitary fibrous tumour',
    '31': '1016 MPNST',
    '30': '1019 UPS',
    '28': '1022 Other sarcomas',
    '37': 'MULTIFOCAL TUMOR',
    '38': 'N/A',
    '21': 'FEMALE',
    '22': 'MALE',
    '25': 'ALIVE',
    '26': 'DEAD',
    '3': '0',
    '2': '1',
    '19': 'Macroscopically complete',
    '20': 'Macroscopically incomplete',
    '18': 'N/A2',
    '14': 'Grade 1 tumor',
    '12': 'Grade 2 tumor',
    '13': 'Grade 3 tumor',
    '15': 'N/A',
    '6': '1004/1007 Liposarcoma',
    '11': '1010 Leiomyosarcoma',
    '8': '1013 Solitary fibrous tumour',
    '10': '1016 MPNST',
    '9': '1019 UPS',
    '7': '1022 Other sarcomas',
    '16': 'MULTIFOCAL TUMOR',
    '17': 'N/A',
    '0': 'FEMALE',
    '1': 'MALE',
    '4': 'ALIVE',
    '5': 'DEAD',
    '45': '0',
    '44': '1',
    '61': 'Macroscopically complete',
    '62': 'Macroscopically incomplete',
    '60': 'N/A2',
    '57': 'Grade 1 tumor',
    '54': 'Grade 2 tumor',
    '55': 'Grade 3 tumor',
    '56': 'N/A',
    '48': '1004/1007 Liposarcoma',
    '53': '1010 Leiomyosarcoma',
    '50': '1013 Solitary fibrous tumour',
    '52': '1016 MPNST',
    '51': '1019 UPS',
    '49': '1022 Other sarcomas',
    '58': 'MULTIFOCAL TUMOR',
    '59': 'N/A',
    '42': 'FEMALE',
    '43': 'MALE',
    '46': 'ALIVE',
    '47': 'DEAD'},
   'mock-1': {'24': 146,
    '23': 130,
    '40': 160,
    '41': 87,
    '39': 29,
    '36': 80,
    '33': 88,
    '34': 103,
    '35': 5,
    '27': 85,
    '32': 39,
    '29': 34,
    '31': 38,
    '30': 41,
    '28': 39,
    '37': 192,
    '38': 84,
    '21': 149,
    '22': 127,
    '25': 146,
    '26': 130,
    '3': 157,
    '2': 147,
    '19': 193,
    '20': 85,
    '18': 26,
    '14': 117,
    '12': 95,
    '13': 91,
    '15': 1,
    '6': 75,
    '11': 41,
    '8': 47,
    '10': 48,
    '9': 41,
    '7': 52,
    '16': 227,
    '17': 77,
    '0': 154,
    '1': 150,
    '4': 157,
    '5': 147,
    '45': 309,
    '44': 281,
    '61': 358,
    '62': 175,
    '60': 57,
    '57': 201,
    '54': 186,
    '55': 197,
    '56': 6,
    '48': 165,
    '53': 82,
    '50': 81,
    '52': 88,
    '51': 82,
    '49': 92,
    '58': 426,
    '59': 164,
    '42': 307,
    '43': 283,
    '46': 309,
    '47': 281}},
  {'Cohort': {'0': 'pelvis_cohort',
    '1': 'pelvis_cohort',
    '2': 'pelvis_cohort',
    '3': 'pelvis_cohort',
    '4': 'pelvis_cohort',
    '5': 'pelvis_cohort',
    '6': 'pelvis_cohort',
    '7': 'rps_cohort',
    '8': 'rps_cohort',
    '9': 'rps_cohort',
    '10': 'rps_cohort',
    '11': 'rps_cohort',
    '12': 'rps_cohort',
    '13': 'rps_cohort',
    '14': 'rps_pelvis_cohort',
    '15': 'rps_pelvis_cohort',
    '16': 'rps_pelvis_cohort',
    '17': 'rps_pelvis_cohort',
    '18': 'rps_pelvis_cohort',
    '19': 'rps_pelvis_cohort',
    '20': 'rps_pelvis_cohort'},
   'Variable': {'0': 'CENSOR',
    '1': 'COMPLETENESS_OF_RESECTION',
    '2': 'FNCLCC_GRADE',
    '3': 'HISTOLOGY',
    '4': 'MULTIFOCALITY',
    '5': 'SEX',
    '6': 'STATUS',
    '7': 'CENSOR',
    '8': 'COMPLETENESS_OF_RESECTION',
    '9': 'FNCLCC_GRADE',
    '10': 'HISTOLOGY',
    '11': 'MULTIFOCALITY',
    '12': 'SEX',
    '13': 'STATUS',
    '14': 'CENSOR',
    '15': 'COMPLETENESS_OF_RESECTION',
    '16': 'FNCLCC_GRADE',
    '17': 'HISTOLOGY',
    '18': 'MULTIFOCALITY',
    '19': 'SEX',
    '20': 'STATUS'},
   'Chi-squared': {'0': 0.0,
    '1': 0.0,
    '2': 0.0,
    '3': 0.0,
    '4': 0.0,
    '5': 0.0,
    '6': 0.0,
    '7': 0.0,
    '8': 0.0,
    '9': 0.0,
    '10': 0.0,
    '11': 0.0,
    '12': 0.0,
    '13': 0.0,
    '14': 0.0,
    '15': 0.0,
    '16': 0.0,
    '17': 0.0,
    '18': 0.0,
    '19': 0.0,
    '20': 0.0},
   'P-value': {'0': 1.0,
    '1': 1.0,
    '2': 1.0,
    '3': 1.0,
    '4': 1.0,
    '5': 1.0,
    '6': 1.0,
    '7': 1.0,
    '8': 1.0,
    '9': 1.0,
    '10': 1.0,
    '11': 1.0,
    '12': 1.0,
    '13': 1.0,
    '14': 1.0,
    '15': 1.0,
    '16': 1.0,
    '17': 1.0,
    '18': 1.0,
    '19': 1.0,
    '20': 1.0}}]]

In [39]:
pd.DataFrame.from_dict(result[0][0])

,Cohort,Variable,Level,mock-1
24,pelvis_cohort,CENSOR,0,146
23,pelvis_cohort,CENSOR,1,130
40,pelvis_cohort,COMPLETENESS_OF_RESECTION,Macroscopically complete,160
41,pelvis_cohort,COMPLETENESS_OF_RESECTION,Macroscopically incomplete,87
39,pelvis_cohort,COMPLETENESS_OF_RESECTION,N/A2,29
...,...,...,...,...
59,rps_pelvis_cohort,MULTIFOCALITY,N/A,164
42,rps_pelvis_cohort,SEX,FEMALE,307
43,rps_pelvis_cohort,SEX,MALE,283
46,rps_pelvis_cohort,STATUS,ALIVE,309
47,rps_pelvis_cohort,STATUS,DEAD,281

In [40]:
pd.DataFrame.from_dict(result[0][1])

               Cohort                   Variable  Chi-squared  P-value
0       pelvis_cohort                     CENSOR          0.0      1.0
1       pelvis_cohort  COMPLETENESS_OF_RESECTION          0.0      1.0
2       pelvis_cohort               FNCLCC_GRADE          0.0      1.0
3       pelvis_cohort                  HISTOLOGY          0.0      1.0
4       pelvis_cohort              MULTIFOCALITY          0.0      1.0
5       pelvis_cohort                        SEX          0.0      1.0
6       pelvis_cohort                     STATUS          0.0      1.0
7          rps_cohort                     CENSOR          0.0      1.0
8          rps_cohort  COMPLETENESS_OF_RESECTION          0.0      1.0
9          rps_cohort               FNCLCC_GRADE          0.0      1.0
10         rps_cohort                  HISTOLOGY          0.0      1.0
11         rps_cohort              MULTIFOCALITY          0.0      1.0
12         rps_cohort                        SEX          0.0      1.0
13         rps_cohort                     STATUS          0.0      1.0
14  rps_pelvis_cohort                     CENSOR          0.0      1.0
15  rps_pelvis_cohort  COMPLETENESS_OF_RESECTION          0.0      1.0
16  rps_pelvis_cohort               FNCLCC_GRADE          0.0      1.0
17  rps_pelvis_cohort                  HISTOLOGY          0.0      1.0
18  rps_pelvis_cohort              MULTIFOCALITY          0.0      1.0
19  rps_pelvis_cohort                        SEX          0.0      1.0
20  rps_pelvis_cohort                     STATUS          0.0      1.0

In [ ]:
#TODO Index: variable, Columns: cohorts, sub_columns: chi-squared, p-value

### 3b. Continuous variables: T-test

## OLD

In [31]:
import psycopg2
import pandas as pd

ModuleNotFoundError: No module named 'psycopg2'

In [ ]:
## Database related
def establish_connection():
    dbname = "omopdb"
    user = "ohdsi"
    password = "ohdsi"
    host = "localhost"
    port = "5432"

    conn = psycopg2.connect(
        dbname=dbname,
        user=user,
        password=password,
        host=host,
        port=port
    )

    cur = conn.cursor()
    return conn, cur

In [ ]:
with open('./query.sql', 'r') as file: query = file.read()
conn, cur = establish_connection()
cur.execute(query)
data = cur.fetchall()
column_names = [desc[0] for desc in cur.description]
df = pd.DataFrame(data, columns=column_names)
print(df)

In [ ]:
# # five_patients_cohort 
# five_patients_cohort_R = sessions.create_cohort(
#     patient_ids=[1,2,3,4,80],
#     features="sarcoma"
# )

# # five_patients_cohort_R.head()

# # TODO: move this to the session algorithm
# five_patients_cohort = common.convert_from_r(five_patients_cohort_R, date_cols=["SURGERY_DATE"])
# five_patients_cohort


# # all_sarcoma_cohort 
# all_sarcoma_cohort_R = sessions.create_cohort(
#     patient_ids=list(range(1,601)),
#     features="sarcoma"
# )

# # all_sarcoma_cohort_R.head()

# # TODO: move this to the session algorithm
# all_sarcoma_cohort = common.convert_from_r(all_sarcoma_cohort_R, date_cols=["SURGERY_DATE"])
# all_sarcoma_cohort


# # women_sarcoma_cohort 
# women_sarcoma_cohort_R = sessions.create_cohort(
#     patient_ids=[2,3,4,5,9,10,11,12,13,16,17,23,31,32,33,37,39,40,42,43,44,49,50,51,54,56,59,62,63,64,65,66,67,68,69,71,73,74,75,77,78,81,83,84,85,92,96,97,100,101,102,105,107,110,111,112,113,118,120,124,125,126,128,129,130,131,136,139,144,145,151,152,153,154,162,167,169,171,184,187,189,195,200,201,202,203,204,206,207,210,211,213,218,225,229,230,232,235,236,237,239,240,245,246,248,249,250,252,253,255,256,259,260,261,263,265,267,268,270,271,273,276,277,278,280,286,289,290,292,293,297,299,300,303,304,306,310,311,314,319,321,325,329,332,333,334,337,341,342,347,349,350,351,356,357,362,365,366,370,371,372,376,377,378,380,381,382,383,384,385,387,388,389,390,391,395,396,400,401,403,405,406,408,410,412,414,415,416,417,419,421,422,425,427,429,431,432,433,437,439,442,446,447,448,450,451,452,455,456,457,460,461,464,465,466,467,469,471,472,475,476,477,478,480,481,483,486,487,489,494,496,499,503,504,505,507,508,509,510,511,512,513,516,517,518,519,521,524,525,527,529,530,532,533,534,535,537,539,540,541,542,543,545,547,548,549,550,551,552,553,554,555,556,557,561,564,565,566,567,568,570,571,575,578,580,582,583,584,585,586,587,588,589,590,594,595,596,597,598,600],
#     features="sarcoma"
# )

# # women_sarcoma_cohort_R.head()

# # TODO: move this to the session algorithm
# women_sarcoma_cohort = common.convert_from_r(women_sarcoma_cohort_R, date_cols=["SURGERY_DATE"])
# women_sarcoma_cohort